### ISSUE TITLE
当一些图片字体过大时,会抛出异常

### ISSUE THREAD

**Issue by quuhua911** [myhub/tr#10]
/home/quh/.conda/envs/pytorch/bin/python /home/quh/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/192.5728.105/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 33817 --file /home/quh/pythonwork/tr/example.py
pydev debugger: process 23924 is connecting

Connected to pydev debugger (build 192.5728.105)
python: /pytorch/third_party/ideep/mkl-dnn/src/common/memory_tracking.hpp:229: void* mkldnn::impl::memory_tracking::registry_t::get(const key_t&, void*) const: Assertion `size() == 0' failed.

**Comment by myhub** [comment]
可以把测试图片发给我吗？我测试下

**Comment by quuhua911** [comment]
您方便加我一下QQ20613622 吗?我用QQ发给您

**Comment by quuhua911** [comment]
(invoice) quh@quh-Z370P-D3:~/pythonwork/tr$ python example.py 
这几个图片都不行
python: /pytorch/third_party/ideep/mkl-dnn/src/common/memory_tracking.hpp:229: void* mkldnn::impl::memory_tracking::registry_t::get(const key_t&, void*) const: Assertion `size() == 0' failed.
已放弃 (核心已转储)
![门牌10](https://user-images.githubusercontent.com/35398080/66297185-c7fdc380-e921-11e9-89ab-f79eeef8cc8c.jpg)
![门牌9](https://user-images.githubusercontent.com/35398080/66297228-dd72ed80-e921-11e9-80fb-e100a3a16fc9.jpg)
![门牌7](https://user-images.githubusercontent.com/35398080/66297327-0d21f580-e922-11e9-8195-285b2ed540ab.png)

**Comment by myhub** [comment]
我这边也复现了这个bug，这个问题需要花点时间排查，会尽快修复
谢谢反馈

**Comment by quuhua911** [comment]
我电脑显卡是1080Ti,内存是48G.另外出问题时没有训练别的深度学习模型.

**Comment by quuhua911** [comment]
就是单纯的有些图片可以识别,有些图片会抛出异常.

**Comment by myhub** [comment]
我再检查下

**Comment by zhangqizky** [comment]
我这边也是会出现这样的问题，麻烦楼主看下

**Comment by myhub** [comment]
> 我这边也是会出现这样的问题，麻烦楼主看下

这个问题比较难复现，有时正常，有时报错

**Comment by zhangqizky** [comment]
好的，谢谢楼主
