### ISSUE TITLE
使用限制咨询

### ISSUE THREAD

**Issue by wckjlu** [myhub/tr#106]
我测试断网的情况下执行出现no server available,是说这个应用必须联网才能使用吗？是否需要授权或者使用次数是否有限制?另外识别是在本地进行吧？还是和后台服务有什么关系?

**Comment by scfw** [comment]
确实是不联网不能用。可以试试PaddleOCR

**Comment by wckjlu** [comment]
谢谢，要使用的设备配置太低了，使用PaddleOCR进行速度太慢，无法使用啊.

**Comment by myhub** [comment]
后面计划把这些限制都取消掉，欢迎关注

**Comment by InvincibleKe** [comment]
请问什么时候能够取消限制呢？或者这个授权应该怎么联系呢？

**Comment by InvincibleKe** [comment]
> 后面计划把这些限制都取消掉，欢迎关注

请问什么时候能够取消限制呢？或者这个授权应该怎么联系呢？

**Comment by lai6964** [comment]
> > 后面计划把这些限制都取消掉，欢迎关注
> 
> 请问什么时候能够取消限制呢？或者这个授权应该怎么联系呢？

请问作者有回复吗？什么时候能够取消限制呢？或者这个授权应该怎么联系呢？

**Comment by myhub** [comment]
use v2.3.1
