### ISSUE TITLE
程序初始化时联网是做了什么？

### ISSUE THREAD

**Issue by yfq512** [myhub/tr#108]
@myhub 感谢作者的分享，效果速度都很优秀，只是这个需要联网的担忧，会不会服务用着用着哪天就突然不能用了呀！能不能大致说一下，联网都做了些什么呀？让我吃个定心丸

**Comment by apoet** [comment]
@yfq512 看一看 https://github.com/DayBreak-u/chineseocr_lite

**Comment by myhub** [comment]
就是检测DNS可不可以访问 ，后面计划把这个限制也取消掉，欢迎关注

**Comment by myhub** [comment]
> @yfq512 看一看 https://github.com/DayBreak-u/chineseocr_lite

chineseocr_lite不错的，还有PaddleOCR之类的

**Comment by myhub** [comment]
更新了
