### ISSUE TITLE
代码错误

### ISSUE THREAD

**Issue by aBlindBoy** [myhub/tr#11]
[2019-10-09 04:21:48,483] ERROR in app: Exception on /ocrRecognize [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "ocrRecognize.py", line 57, in ocr_recognize
    results = run(gray_pil)
  File "/usr/local/lib/python3.6/dist-packages/tr-1.1.2.2-py3.6.egg/tr/tr.py", line 244, in run
    rect_arr = numpy.int0(rect_arr)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by novioleo** [comment]
pull最新代码即可 @aBlindBoy




------------------ 原始邮件 ------------------
发件人: "aBlindBoy"<notifications@github.com>;
发送时间: 2019年10月9日(星期三) 中午12:26
收件人: "myhub/tr"<tr@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [myhub/tr] 代码错误 (#11)




[2019-10-09 04:21:48,483] ERROR in app: Exception on /ocrRecognize [POST]
 Traceback (most recent call last):
 File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2446, in wsgi_app
 response = self.full_dispatch_request()
 File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1951, in full_dispatch_request
 rv = self.handle_user_exception(e)
 File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1820, in handle_user_exception
 reraise(exc_type, exc_value, tb)
 File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
 raise value
 File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
 rv = self.dispatch_request()
 File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
 return self.view_functionsrule.endpoint
 File "ocrRecognize.py", line 57, in ocr_recognize
 results = run(gray_pil)
 File "/usr/local/lib/python3.6/dist-packages/tr-1.1.2.2-py3.6.egg/tr/tr.py", line 244, in run
 rect_arr = numpy.int0(rect_arr)
 TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by aBlindBoy** [comment]
好的，谢谢大佬

**Comment by aBlindBoy** [comment]
terminate called after throwing an instance of 'c10::Error'
  what():  weakcount_.load() == 0 INTERNAL ASSERT FAILED at /pytorch/c10/util/intrusive_ptr.h:96, please report a bug to PyTorch. Tried to destruct an intrusive_ptr_target that still has weak_intrusive_ptr to it (~intrusive_ptr_target at /pytorch/c10/util/intrusive_ptr.h:96)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f272baf9553 in /usr/local/lib/python3.6/dist-packages/tr-1.1.2.2-py3.6.egg/tr/../libtorch/lib/libc10.so)
frame #1: <unknown function> + 0x20cf9 (0x7f272bae9cf9 in /usr/local/lib/python3.6/dist-packages/tr-1.1.2.2-py3.6.egg/tr/../libtorch/lib/libc10.so)
frame #2: <unknown function> + 0x2b8a7 (0x7f272baf48a7 in /usr/local/lib/python3.6/dist-packages/tr-1.1.2.2-py3.6.egg/tr/../libtorch/lib/libc10.so)
frame #3: <unknown function> + 0x7f47e (0x7f273847b47e in /usr/local/lib/python3.6/dist-packages/tr-1.1.2.2-py3.6.egg/tr/libtr.so)
frame #4: tr_detect + 0x1cd (0x7f273847026d in /usr/local/lib/python3.6/dist-packages/tr-1.1.2.2-py3.6.egg/tr/libtr.so)
frame #5: ffi_call_unix64 + 0x4c (0x7f2745cfddae in /usr/lib/x86_64-linux-gnu/libffi.so.6)
frame #6: ffi_call + 0x22f (0x7f2745cfd71f in /usr/lib/x86_64-linux-gnu/libffi.so.6)
frame #7: _ctypes_callproc + 0x2b4 (0x7f2745f115d4 in /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so)
frame #8: <unknown function> + 0x11d64 (0x7f2745f11d64 in /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>
frame #10: python() [0x509ad3]
frame #12: python() [0x507125]
frame #13: python() [0x508fa0]
frame #14: python() [0x50999d]
frame #16: python() [0x507125]
frame #17: python() [0x508fa0]
frame #18: python() [0x50999d]
frame #20: python() [0x507125]
frame #21: python() [0x5881aa]
frame #24: python() [0x508c69]
frame #25: python() [0x50999d]
frame #27: python() [0x508c69]
frame #28: python() [0x50999d]
frame #30: python() [0x508c69]
frame #31: python() [0x50999d]
frame #34: python() [0x5940d1]
frame #35: python() [0x549f41]
frame #37: python() [0x509ad3]
frame #39: python() [0x507125]
frame #40: python() [0x508fa0]
frame #41: python() [0x50999d]
frame #43: python() [0x507125]
frame #44: python() [0x508fa0]
frame #45: python() [0x50999d]
frame #47: python() [0x508c69]
frame #48: python() [0x50999d]
frame #50: python() [0x508c69]
frame #51: python() [0x50999d]
frame #53: python() [0x508c69]
frame #54: python() [0x50999d]
frame #57: python() [0x5940d1]
frame #58: python() [0x54945f]
frame #59: python() [0x550b91]
frame #61: python() [0x509ad3]
frame #63: python() [0x508c69]

Aborted

**Comment by novioleo** [comment]
应该是你参数错误，出现了递归调用。



------------------ 原始邮件 ------------------
发件人: "aBlindBoy"<notifications@github.com>; 
发送时间: 2019年10月9日(星期三) 下午5:08
收件人: "myhub/tr"<tr@noreply.github.com>; 
抄送: "北国枫叶。"<744351893@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [myhub/tr] 代码错误 (#11)




terminate called after throwing an instance of 'c10::Error'
 what():  weakcount_.load() == 0 INTERNAL ASSERT FAILED at /pytorch/c10/util/intrusive_ptr.h:96, please report a bug to PyTorch. Tried to destruct an intrusive_ptr_target that still has weak_intrusive_ptr to it (~intrusive_ptr_target at /pytorch/c10/util/intrusive_ptr.h:96)
 frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f272baf9553 in /usr/local/lib/python3.6/dist-packages/tr-1.1.2.2-py3.6.egg/tr/../libtorch/lib/libc10.so)
 frame #1:  + 0x20cf9 (0x7f272bae9cf9 in /usr/local/lib/python3.6/dist-packages/tr-1.1.2.2-py3.6.egg/tr/../libtorch/lib/libc10.so)
 frame #2:  + 0x2b8a7 (0x7f272baf48a7 in /usr/local/lib/python3.6/dist-packages/tr-1.1.2.2-py3.6.egg/tr/../libtorch/lib/libc10.so)
 frame #3:  + 0x7f47e (0x7f273847b47e in /usr/local/lib/python3.6/dist-packages/tr-1.1.2.2-py3.6.egg/tr/libtr.so)
 frame #4: tr_detect + 0x1cd (0x7f273847026d in /usr/local/lib/python3.6/dist-packages/tr-1.1.2.2-py3.6.egg/tr/libtr.so)
 frame #5: ffi_call_unix64 + 0x4c (0x7f2745cfddae in /usr/lib/x86_64-linux-gnu/libffi.so.6)
 frame #6: ffi_call + 0x22f (0x7f2745cfd71f in /usr/lib/x86_64-linux-gnu/libffi.so.6)
 frame #7: _ctypes_callproc + 0x2b4 (0x7f2745f115d4 in /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so)
 frame #8:  + 0x11d64 (0x7f2745f11d64 in /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so)
 
 frame #10: python() [0x509ad3]
 frame #12: python() [0x507125]
 frame #13: python() [0x508fa0]
 frame #14: python() [0x50999d]
 frame #16: python() [0x507125]
 frame #17: python() [0x508fa0]
 frame #18: python() [0x50999d]
 frame #20: python() [0x507125]
 frame #21: python() [0x5881aa]
 frame #24: python() [0x508c69]
 frame #25: python() [0x50999d]
 frame #27: python() [0x508c69]
 frame #28: python() [0x50999d]
 frame #30: python() [0x508c69]
 frame #31: python() [0x50999d]
 frame #34: python() [0x5940d1]
 frame #35: python() [0x549f41]
 frame #37: python() [0x509ad3]
 frame #39: python() [0x507125]
 frame #40: python() [0x508fa0]
 frame #41: python() [0x50999d]
 frame #43: python() [0x507125]
 frame #44: python() [0x508fa0]
 frame #45: python() [0x50999d]
 frame #47: python() [0x508c69]
 frame #48: python() [0x50999d]
 frame #50: python() [0x508c69]
 frame #51: python() [0x50999d]
 frame #53: python() [0x508c69]
 frame #54: python() [0x50999d]
 frame #57: python() [0x5940d1]
 frame #58: python() [0x54945f]
 frame #59: python() [0x550b91]
 frame #61: python() [0x509ad3]
 frame #63: python() [0x508c69]
 
Aborted
 
&mdash;

**Comment by aBlindBoy** [comment]
我贴下代码。这个是这样调用的吧，图片太多的话，就像刚才那样报错了，大佬帮帮忙看下，感谢

@app.route('/ocrRecognize', methods=['POST'])
def ocr_recognize():

    if request.method == 'POST':
        # 上传文件
        fname = request.files.get('file')

        # 图片处理
        img_pil = Image.open(fname)
        MAX_SIZE = 2000
        if img_pil.height > MAX_SIZE or img_pil.width > MAX_SIZE:
            scale = max(img_pil.height / MAX_SIZE, img_pil.width / MAX_SIZE)
            new_width = int(img_pil.width / scale + 0.5)
            new_height = int(img_pil.height / scale + 0.5)
            img_pil = img_pil.resize((new_width, new_height), Image.BICUBIC)

        # print(img_pil.width, img_pil.height)
        gray_pil = img_pil.convert("L")

        results = run(gray_pil)
        print(type(results))
        if results is not None:
            text = []
            confidence = []
            locations = []
            for i in range(len(results)):
                locations.append(str(list(results[i][0])))
                text.append(results[i][1])
                confidence.append(results[i][2])
            data = {
                "code": "200",
                "text": text,
                "confidence": str(confidence),
                "locations": locations
            }
        else:
            data = {
                "code": "400",
                "text": [],
                "confidence": [],
                "locations": []
            }
        return jsonify(data)

**Comment by myhub** [comment]
是不是并发的问题？模型目前不支持并发调用的。需要等待上一次调用结束后再调用

**Comment by novioleo** [comment]
目前看起来是的。我感觉


 
---原始邮件---
发件人: "Dream"<notifications@github.com&gt;
发送时间: 2019年10月10日 08:22:17
收件人: "myhub/tr"<tr@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Tao Luo"<744351893@qq.com&gt;;
主题: Re: [myhub/tr] 代码错误 (#11)



是不是并发的问题？模型目前不支持并发调用的。需要等待上一次调用结束后再调用

**Comment by aBlindBoy** [comment]
这个一次识别一张图片和一次识别多张图片，效率是一样的吧

**Comment by novioleo** [comment]
你弄到队列里面，单消费者的异步计算呗


 
---原始邮件---
发件人: "aBlindBoy"<notifications@github.com&gt;
发送时间: 2019年10月10日 09:01:56
收件人: "myhub/tr"<tr@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Tao Luo"<744351893@qq.com&gt;;
主题: Re: [myhub/tr] 代码错误 (#11)



这个一次识别一张图片和一次识别多张图片，效率是一样的吧

**Comment by 498798305** [comment]
你好 问一下 这个源码克隆下来在windows上能跑起来么

**Comment by myhub** [comment]
> 你好 问一下 这个源码克隆下来在windows上能跑起来么

之前做过Windows版本的，发现速度太慢，就暂时不做了
