### ISSUE TITLE
怎么联系，商务合作，价格可谈

### ISSUE THREAD

**Issue by liuke0002** [myhub/tr#110]
我的联系方式 微信：18710890605

**Comment by liuke0002** [comment]
性能和准确度 需满足我们的项目需求

**Comment by myhub** [comment]
建议用免费版本的TR，因为我当时做OCR是为了学习深度学习技术，不想做成商用的

**Comment by znsoftm** [comment]
可以使用 RapidOCR ,提供 商业 支持
