### ISSUE TITLE
tr.run("xx.jpg") 报错：basic_string::_M_construct null not valid

### ISSUE THREAD

**Issue by hnwlxywns** [myhub/tr#117]
操作系统信息：
`[root@localhost script]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"`

执行识别过程：
`[root@localhost script]# python3
Python 3.7.2 (default, Jul 31 2020, 16:52:19) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tr
tr 2.3.0 https://github.com/myhub/tr
>>> t = tr.run("./sfz.jpg")
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
已放弃
`
通过Google查询 貌似是这个问题：
https://stackoverflow.com/questions/54429231/how-to-fix-stdlogic-error-what-basic-string-m-construct-null-not-valid

但是无法修改c++代码， 因此，请大佬关注一下，是否编码在centos操作系统有问题？？？

**Comment by myhub** [comment]
已知centos6系统是不行的
ubuntu16可以
