### ISSUE TITLE
请问如何限制使用的核心数量

### ISSUE THREAD

**Issue by ykallan** [myhub/tr#118]
每次跑起这个tr进行识别的时候，都会占满所有的cpu资源，所有核心都会被占用，有没有什么办法，可以限制一下使用的核心数量嘛，目前部署在本地的服务器上，跑满cpu可能会影响到其他的服务，不知道有没有办法限制一下

**Comment by myhub** [comment]
onnxruntime新版本可能有限制 线程数 这样的 API，没研究过
docker是可以限制程序占用资源的

**Comment by znsoftm** [comment]
sessionOptions.SetInterOpNumThreads(nNumThread);
