### ISSUE TITLE
识别信息不全、新旧版本识别结果对比、识别速度如何提升等

### ISSUE THREAD

**Issue by lilyliling** [myhub/tr#12]
1、图片不做任何预处理直接识别信息不全，已查看ctpn切割保存在tmp文件的图片，某些切割是完整的，识别信息不完整；
2、使用MAX_SIZE压缩后再识别个别字符易识别错0易识别成O，并且把 原来的img_pil = img_pil.resize((new_width, new_height), Image.BICUBIC)改成img_pil = img_pil.resize((new_width, new_height), Image.ANTIALIAS)，高质量压缩也无效；
3、最新更新的版本与上一版本对比，结果显示之前的版本效果反而更好，新版本%识别不出来；
4、可以提高识别速度吗？测试了您的离线版本与百度在线版本，识别速度分别在4s与1s左右，您的方法还可以提高识别速度吗？备注tr.py文件已优化部分代码，只能控制在3s左右；
5、您公开的ctpn与crnn封装成C++与.so文件了，如何训练自己的识别模型呢？

**Comment by myhub** [comment]
0 O识别错误的问题我这边正在解决，主要是因为很多字体里面O 0基本一样，需要优化，速度的问题换成GPU就立刻解决了，如果只能用CPU的话可以尝试一次识别多个文本行

新的版本总体上效果应该更好的，如果对某些样本效果反而不如以前的也很可能的，精度会持续优化的，如果可以把错误的样本发给我，问题很快就可以解决

模型后续有考虑开源的，不过现在还没完全开源，因为需要一些资金支持研发，纯粹依靠开源社区的力量比较难把OCR做到商业级水平，因为没完全开源用户没法加入样本自己训练

**Comment by lilyliling** [comment]
很感谢作者的认真回复与解答，测试显示问题的样本放在附件麻烦查收！
另外想咨询下几个问题：
1、使用GPU该如何调用程序，相关程序是否需要更改？
2、CPU一次识别多个文本行，CTPN切割后，全部扔到CRNN一次识别吗？




------------------ 原始邮件 ------------------
发件人: "Dream"<notifications@github.com>;
发送时间: 2019年10月16日(星期三) 晚上7:00
收件人: "myhub/tr"<tr@noreply.github.com>;
抄送: "轶然"<1319904357@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [myhub/tr] 识别信息不全、新旧版本识别结果对比、识别速度如何提升等 (#12)




0 O识别错误的问题我这边正在解决，主要是因为很多字体里面O 0基本一样，需要优化，速度的问题换成GPU就立刻解决了，如果只能用CPU的话可以尝试一次识别多个文本行
 
新的版本总体上效果应该更好的，如果对某些样本效果反而不如以前的也很可能的，精度会持续优化的，如果可以把错误的样本发给我，问题很快就可以解决
 
模型后续有考虑开源的，不过现在还没完全开源，因为需要一些资金支持研发，纯粹依靠开源社区的力量比较难把OCR做到商业级水平，因为没完全开源用户没法加入样本自己训练

**Comment by myhub** [comment]
可以加我的QQ 3228648623
我没找到附件的下载链接

**Comment by novioleo** [comment]
你暴露了。。哈哈哈哈哈哈




------------------ 原始邮件 ------------------
发件人: "Dream"<notifications@github.com>;
发送时间: 2019年10月17日(星期四) 上午10:34
收件人: "myhub/tr"<tr@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [myhub/tr] 识别信息不全、新旧版本识别结果对比、识别速度如何提升等 (#12)




可以加我的QQ 3228648623
 我没找到附件的下载链接

**Comment by myhub** [comment]
哈哈，多交流

**Comment by aBlindBoy** [comment]
哈哈，我也想知道怎么设置成GPU的
