### ISSUE TITLE
请问可以分享一下CRNN的字典吗？

### ISSUE THREAD

**Issue by qiyuhou** [myhub/tr#120]
请问可以分享一下CRNN的字典吗？
https://raw.githubusercontent.com/myhub/tr/master/tr/char_table.txt
测试了下并不是这个字典？

**Comment by myhub** [comment]
https://github.com/myhub/tr/blob/master/tr/char_table.txt

**Comment by qiyuhou** [comment]
> https://github.com/myhub/tr/blob/master/tr/char_table.txt

我看可以识别出勾号√，但是字典里并没有？

**Comment by nissansz** [comment]
> 请问可以分享一下CRNN的字典吗？ https://raw.githubusercontent.com/myhub/tr/master/tr/char_table.txt 测试了下并不是这个字典？

你好，想问一下，在哪里下载可用的日文模型和字典，或怎样生成日文模型和字典？微信 nlanguage
