### ISSUE TITLE
项目中的crnn.bin能否自己训练

### ISSUE THREAD

**Issue by kuyoeku** [myhub/tr#125]
项目中的crnn.bin能否自己训练？有些字符识别准确度不是很高，想自己训练一下。是否能用crnn的训练方式训练完后改成crnn.bin

**Comment by Ronghefeng** [comment]
> 项目中的crnn.bin能否自己训练？有些字符识别准确度不是很高，想自己训练一下。是否能用crnn的训练方式训练完后改成crnn.bin
I really want to know, too

**Comment by myhub** [comment]
CRNN训练代码不是什么核心技术的，代码随便找哪家star多的开源的都差不多的
主要还是训练数据，包含样本合成代码以及人工标注的样本
这个开源的不多，因为真实数据涉及到隐私，合成数据的话字体/语料什么的也都是有版权的
