### ISSUE TITLE
部分中文在char_table.txt中没有，比如 喆 添加后未生效，微信cw157776460

### ISSUE THREAD

**Issue by cenwei1234** [myhub/tr#126]
![image](https://user-images.githubusercontent.com/28823778/153101291-f986b440-784e-40c2-b086-844b3a6388c9.png)
有些汉字没有，添加后重新启动未生效

**Comment by cenwei1234** [comment]
比如  喆

**Comment by myhub** [comment]
新字符需要重新训练网络的，目前新版本正在研发中，会优先提高速度和精度，暂时不计划支持新字符和其他语言

**Comment by cenwei1234** [comment]
> 新字符需要重新训练网络的，目前新版本正在研发中，会优先提高速度和精度，暂时不计划支持新字符和其他语言

很高兴能收到您的答复，预计什么时候可以上线新版本呀
