### ISSUE TITLE
安装后运行失败

### ISSUE THREAD

**Issue by 81519434** [myhub/tr#13]
![image](https://user-images.githubusercontent.com/9690089/66976553-e0fe3580-f0d4-11e9-8154-53b7546e5cf0.png)
![image](https://user-images.githubusercontent.com/9690089/66976558-e52a5300-f0d4-11e9-9f78-6875e3d0e1e7.png)

 这种情况应该怎么处理？

**Comment by myhub** [comment]
目前只测试过ubuntu系统，你用的什么系统

**Comment by 81519434** [comment]
好的谢谢
