### ISSUE TITLE
对于新字符，下次什么时候更新呀？目前在试用，有些字没识别出来，所以问下您，打扰了

### ISSUE THREAD

**Issue by cenwei1234** [myhub/tr#130]
看您评论说 新字符需要重新训练网络的，目前新版本正在研发中，会优先提高速度和精度，预计什么时候可以更新呀，期待您的答复

**Comment by myhub** [comment]
我这边尝试了一些单阶段网络,目前测试了很多网络结构,效果不是特别理想,因为不是采用现有成熟技术,研发周期太难预料了

**Comment by myhub** [comment]
近期主要在优化多行CRNN，https://github.com/myhub/tr/tree/master/crnn_for_text_with_multiple_lines
暂时不会添加新字符
