### ISSUE TITLE
GPU下图像识别，有时候需要重启应用才能识别

### ISSUE THREAD

**Issue by cenwei1234** [myhub/tr#132]
Dear myhub:
应用部署在GPU上，有时候识别不出来，需要重启应用，这个怎么解决呀

**Comment by cenwei1234** [comment]
![图片](https://user-images.githubusercontent.com/28823778/159154657-d883e949-57bf-4f9b-a45f-ec6457fb4243.png)

**Comment by myhub** [comment]
真没遇到过，不过为了保证服务可靠性，如果出现异常可以重新初始化一下，不用重启的，初始化是tr.init函数

**Comment by cenwei1234** [comment]
> 

感谢myhub回复，没有异常，只是返回空值

**Comment by cenwei1234** [comment]
请问下，是这样么，期待您的回复，谢谢
![图片](https://user-images.githubusercontent.com/28823778/160056016-daba2ac1-efeb-4783-bf47-36d72a80545d.png)

**Comment by cenwei1234** [comment]
Dear myhub，还有个问题也想咨询您，因为在用的过程中发现的，也不好复现，如下：
（GPU）有时候图片传进去获取的值为空值，有时候值是有，但是就几个识别不准确的字，也没报异常，但是重启后就能正常识别，想咨询您这个如何优化呀。万分感谢
