### ISSUE TITLE
能否提供权重和模型参数供大家微调呢

### ISSUE THREAD

**Issue by heguodui** [myhub/tr#134]
模型准确率很高，但是在一些特定的识别任务当中还有些错误，所以请问一下能否提供模型参数和权重供我们在自己的任务上做微调呢？

**Comment by myhub** [comment]
我最近也在优化,希望可以进一步提升检测识别精度,欢迎关注
如果需要训练自己的模型 推荐PaddleOCR,那个比较适合个人定制
