### ISSUE TITLE
外形近似的字，如日曰等，怎样训练才能达到高准确度？微信nlanguage

### ISSUE THREAD

**Issue by nissansz** [myhub/tr#135]
外形近似的字，如日曰等，怎样训练才能达到高准确度？微信nlanguage

**Comment by myhub** [comment]
加入识别错误的样本到训练集就好了

**Comment by nissansz** [comment]
是不是训练数据和实际数据约接近，效果越好？
背景是深色，浅色，黑色，白色，有什么影响吗？

**Comment by myhub** [comment]
那肯定的呀 要么合成样本,要么收集真实样本

**Comment by nissansz** [comment]
你的训练是怎么做到不同背景都能通用识别的？我感觉用paddle训练的，会受背景影响。

**Comment by nissansz** [comment]
如果用你的数据，去通过paddle训练，也能达到一样的准确率吗？

**Comment by myhub** [comment]
只要数据够肯定可以的,但是OCR的文本样本一般涉及到隐私,或者是字体也都是有版权的,没人大规模开放下载的

**Comment by nissansz** [comment]
我用一条数据，生成了300遍。
的确可以彩图，二值化图都能正确识别。
后面我分批生成，没3000条，生成一批3000*300张
训练完一批再训练下一批
这样训练可以吗？对正确率有什么影响吗？

**Comment by myhub** [comment]
一次才3000条 做各种增强, 会不会太少了
我觉得要加2个0 一次3000 00 条,生成3000 00 * 300张 然后训练

**Comment by myhub** [comment]
我这边也只有一台很多年前买的笔记本训练OCR模型, 只有一张1060显卡
我都想办法把样本做到千万级别了,样本一点点没啥用的

**Comment by nissansz** [comment]
千万级别，不同文字行？
训练完一个epoch千万级别数据，然后再次生成千万级别不同背景，不同字体等，训练。
然后重复生成200+遍训练？

**Comment by nissansz** [comment]
你是GTX1060显卡？
和RTX3060显卡有多大差别？

你训练千万级别1个epoch要多久？训练多少个epoch才能达到较高 准确度？

**Comment by myhub** [comment]
GTX1060显卡, 训练很慢的, 1000万的样本好几天才能训练1轮的

**Comment by nissansz** [comment]
用什么显卡比较合适？
https://blog.csdn.net/u012160945/article/details/118754257 
这里说3060显卡比1060的慢4倍

**Comment by nissansz** [comment]
你是用什么操作系统训练？

**Comment by nissansz** [comment]
如果用paddle训练是不是要用rec_resnet_stn_bilstm_att.yml这个配置文件来训练，准确率才会高？

https://zhuanlan.zhihu.com/p/268761718

模型训练调优
Q2.3.1：如何更换文本检测/识别的backbone？
A：无论是文字检测，还是文字识别，骨干网络的选择是预测效果和预测效率的权衡。一般，选择更大规模的骨干网络，例如ResNet101_vd，则检测或识别更准确，但预测耗时相应也会增加。而选择更小规模的骨干网络，例如MobileNetV3_small_x0_35，则预测更快，但检测或识别的准确率会大打折扣。幸运的是不同骨干网络的检测或识别效果与在ImageNet数据集图像1000分类任务效果正相关。[飞桨图像分类套件PaddleClas](https://link.zhihu.com/?target=https%3A//github.com/PaddlePaddle/PaddleClas)汇总了ResNet_vd、Res2Net、HRNet、MobileNetV3、GhostNet等23种系列的分类网络结构，在上述图像分类任务的top1识别准确率，GPU(V100和T4)和CPU(骁龙855)的预测耗时以及相应的[117个预训练模型下载地址](https://link.zhihu.com/?target=https%3A//paddleclas.readthedocs.io/zh_CN/latest/models/models_intro.html)。

**Comment by nissansz** [comment]
好像用paddle训练了4个epoch （3000*300）, 准确率也没达到0.99以上。
你是千万张，训练多少个epoch达到很高的准确度？

[2022/04/26 23:25:53] root INFO: epoch: [2/50000], iter: 35690, lr: 0.001000, loss: 0.526568, acc: 0.906222, norm_edit_dis: 0.990198, reader_cost: 0.00110 s, batch_cost: 0.24456 s, samples: 320, ips: 130.84628
[2022/04/26 23:26:03] root INFO: epoch: [2/50000], iter: 35700, lr: 0.001000, loss: 0.584383, acc: 0.906222, norm_edit_dis: 0.989373, reader_cost: 0.00184 s, batch_cost: 0.19996 s, samples: 320, ips: 160.03165
[2022/04/26 23:26:13] root INFO: epoch: [2/50000], iter: 35710, lr:

**Comment by myhub** [comment]
paddle我没用过，我最近在优化文本检测部分
感觉用啥网络效果都差不多的，关键还是看训练数据啦

**Comment by nissansz** [comment]
大概训练到准确率多少就比较好了？

s: 320, ips: 288.43552
[2022/04/28 17:32:51] root INFO: epoch: [1/500], iter: 4680, lr: 0.001000, loss: 0.406836, acc: 0.937471, norm_edit_dis: 0.991853, reader_cost: 0.00033 s, batch_cost: 0.11131 s, samples: 320, ips: 287.47788
[2022/04/28 17:33:02] root INFO: epoch: [1/500], iter: 4690, lr: 0.001000, loss: 0.587524, acc: 0.937471, norm_edit_dis: 0.987576, reader_cost: 0.00032 s, batch_cost: 0.11036 s, samples: 320, ips: 289.95862
[2022/04/28 17:33:14] root INFO: epoch: [1/500], iter: 4700, lr: 0.001000, loss: 0.331913, acc: 0.937471, norm_edit_dis: 0.996229, reader_cost: 0.00032 s, batch_cost: 0.11127 s, samples: 320, ips: 287.58247
[2022/04/28 17:33:25] root INFO: epoch: [1/500], iter: 4710, lr: 0.001000, loss: 0.38268

**Comment by myhub** [comment]
> 如果用paddle训练是不是要用rec_resnet_stn_bilstm_att.yml这个配置文件来训练，准确率才会高？
> 
> https://zhuanlan.zhihu.com/p/268761718
> 
> 模型训练调优 Q2.3.1：如何更换文本检测/识别的backbone？ A：无论是文字检测，还是文字识别，骨干网络的选择是预测效果和预测效率的权衡。一般，选择更大规模的骨干网络，例如ResNet101_vd，则检测或识别更准确，但预测耗时相应也会增加。而选择更小规模的骨干网络，例如MobileNetV3_small_x0_35，则预测更快，但检测或识别的准确率会大打折扣。幸运的是不同骨干网络的检测或识别效果与在ImageNet数据集图像1000分类任务效果正相关。[飞桨图像分类套件PaddleClas](https://link.zhihu.com/?target=https%3A//github.com/PaddlePaddle/PaddleClas)汇总了ResNet_vd、Res2Net、HRNet、MobileNetV3、GhostNet等23种系列的分类网络结构，在上述图像分类任务的top1识别准确率，GPU(V100和T4)和CPU(骁龙855)的预测耗时以及相应的[117个预训练模型下载地址](https://link.zhihu.com/?target=https%3A//paddleclas.readthedocs.io/zh_CN/latest/models/models_intro.html)。

没有你说的这么玄乎吧，文本行特征比较简单，所以我觉得轻量级的backbone 类似resnet18就足够了，也不要什么imagenet预训练权重

文本行检测难点还是字体大小变化范围大，各种噪声干扰多，字体也多，导致训练样本比较难覆盖全部的真实情况

**Comment by nissansz** [comment]
那用paddle的哪个配置文件比较好？怎么配置？我现在的配置如下
rec_japan_lite_train.yml
[rec_japan_lite_train1.zip](https://github.com/myhub/tr/files/8581563/rec_japan_lite_train1.zip)

**Comment by myhub** [comment]
没用过paddleocr，回答不出来，我不想做个跟paddle差不多的ocr，没啥意义

**Comment by nissansz** [comment]
可以发你的训练代码来训练试试？我想训练日语模型

**Comment by nissansz** [comment]
现在训练的图片如下，有没有什么要改进的地方？

![image](https://user-images.githubusercontent.com/41010669/165847602-0b163cdd-3f6d-4cfd-bf2d-59bc37a2ce99.png)

**Comment by myhub** [comment]
> 

这样本我觉得还是很单一的，训练出来的模型在训练集上准确度会很高，但是拿到实际场景会很难用的

**Comment by nissansz** [comment]
你的样本是什么样子的？可以截图看看吗？
我想准备类似的样本训练试试

**Comment by nissansz** [comment]
两种训练方法，哪种好？
1. 分批生成，每批1000*300次重复不同字体
2. 一次生成30000，没有重复

**Comment by myhub** [comment]
> 你的样本是什么样子的？可以截图看看吗？ 我想准备类似的样本训练试试

样本越接近真实样本越好啦，尤其是那些不太清晰的真实样本

**Comment by nissansz** [comment]
真实样本，很多都是书籍印刷体，很清晰的，很少不清晰的

**Comment by myhub** [comment]
我也是个深度学习初学者，怕在这里回答误导了大家，后面可以发邮件哈 anycode@yahoo.com
