### ISSUE TITLE
terminate called after throwing an instance of 'cv::Exception'   what():  OpenCV(4.3.0) /home/hgzn/share/opencv-4.3.0/modules/core/src/matrix.cpp:466: error: (-215:Assertion failed) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function 'Mat'

### ISSUE THREAD

**Issue by cenwei1234** [myhub/tr#136]
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.3.0) /home/hgzn/share/opencv-4.3.0/modules/core/src/matrix.cpp:466: error: (-215:Assertion failed) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function 'Mat'
稳定运行一段时间，突然报这个错误，然后应用直接挂了

**Comment by myhub** [comment]
第一次有人报这个错误，应该可能是遇到了一些很特殊的情况，比如检测到文本框的大小是0而程序有没做异常处理导致的

**Comment by myhub** [comment]
我最近隔离在家，正在开发新版本，新版本文本检测精度也是大幅度提升的，您可以关注新版本

**Comment by cenwei1234** [comment]
好的收到，期待

**Comment by cenwei1234** [comment]
> 我最近隔离在家，正在开发新版本，新版本文本检测精度也是大幅度提升的，您可以关注新版本

好的收到，期待！如果还能识别银行卡卡号那最好了

**Comment by myhub** [comment]
> > 我最近隔离在家，正在开发新版本，新版本文本检测精度也是大幅度提升的，您可以关注新版本
> 
> 好的收到，期待！如果还能识别银行卡卡号那最好了

可以发几张银行卡样本给我，这个更新尽可能支持掉 anycode@yahoo.com

**Comment by cenwei1234** [comment]
> > > 我最近隔离在家，正在开发新版本，新版本文本检测精度也是大幅度提升的，您可以关注新版本
> > 
> > 
> > 好的收到，期待！如果还能识别银行卡卡号那最好了
> 
> 可以发几张银行卡样本给我，这个更新尽可能支持掉 [anycode@yahoo.com](mailto:anycode@yahoo.com)

好的收到，已发您邮箱，请查收哦

**Comment by newledge** [comment]
同样的问题，什么时间能解决？
