### ISSUE TITLE
安装好后运行测试文件失败

### ISSUE THREAD

**Issue by 81519434** [myhub/tr#14]
![image](https://user-images.githubusercontent.com/9690089/66981195-9a650700-f0e5-11e9-938b-9259f28b903f.png)
这个怎么解决？
按照指引，安装好依赖和软件了。
环境:ubuntu18,Python 3.6.8

**Comment by myhub** [comment]
这个警告应该没影响的，非桌面系统没法显示图片，可以通过别的方式查看生成的图片

**Comment by 81519434** [comment]
好的，非常感谢
