### ISSUE TITLE
手写识别一般哦

### ISSUE THREAD

**Issue by nne998** [myhub/tr#145]
<img width="1308" alt="1" src="https://user-images.githubusercontent.com/148901/175277880-3d808708-8496-4eab-8855-fc5b8284b8ac.png">

**Comment by nne998** [comment]
<img width="1261" alt="222" src="https://user-images.githubusercontent.com/148901/175280180-f520f8d9-ec0b-49c2-9f2d-710388a94824.png">

**Comment by myhub** [comment]
训练样本中都没有手写字，能达到这个效果已经很不错了

**Comment by nne998** [comment]
看下有没有计划加入手写识别？

这里有一些数据集 https://zhuanlan.zhihu.com/p/24698483

**Comment by myhub** [comment]
手写字确实是个难点，因为没法收集到大量数据，也没法用代码合成，所以暂时不考虑支持
