### ISSUE TITLE
在3090显卡上启动gpu就卡死

### ISSUE THREAD

**Issue by dixon1983** [myhub/tr#148]
在3090显卡上启动
![微信图片_20220716100033](https://user-images.githubusercontent.com/35091088/179334434-284250f0-2666-4685-9a9f-999450fe42cd.png)
gpu就卡死，显示在tr_gpu 2.3.1 https://github.com/myhub/tr 就不动了

**Comment by dixon1983** [comment]
在网上找了很多文章，终于找到原因，RT3090显卡只支持CUDA11以上，您这个tr只能用CUDA10.1,所以好像无解了。不知道作者能否升级一下？

**Comment by myhub** [comment]
不好意思, 由于工作太忙, 暂时没有时间升级维护
