### ISSUE TITLE
gpu再容器下执行报错

### ISSUE THREAD

**Issue by yuanhaisu** [myhub/tr#149]
报错提示：
`root@b653069529fb:/home/tr# python test-multi-thread.py 

tr_gpu 2.3.1 https://github.com/myhub/tr

2022-07-16 03:11:17.016232421 [E:onnxruntime:, sequential_executor.cc:281 Execute] Non-zero status code returned while running Relu node. Name:'Relu_2' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device
Non-zero status code returned while running Relu node. Name:'Relu_2' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device
pure virtual method called
terminate called without an active exception
Aborted (core dumped)`

驱动信息：
`root@b653069529fb:/home/tr# nvidia-smi
Sat Jul 16 03:19:19 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.57       Driver Version: 515.57       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:06:00.0 Off |                  N/A |
| 31%   29C    P0    N/A / 240W |      0MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+`

cuda版本：
`root@b653069529fb:/home/tr# nvcc -V

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243`

**Comment by myhub** [comment]
不支持较新版本的GPU
