### ISSUE TITLE
大佬，请问计划支持windows吗！

### ISSUE THREAD

**Issue by huangxin168** [myhub/tr#150]

**Comment by myhub** [comment]
当前版本没计划支持windows的，

**Comment by yw9381** [comment]
@myhub 
可以给一份在windows下如何使用crnn.bin及ctpn.bin的方法，以及win下编译libtr.so libonnxruntime.so的方法么

**Comment by suings** [comment]
同求,tag2.3.0可以在win10上运行,但是win11上报错
    _libc.tr_init(pid, id, c_ptr(model), arg)
OSError: exception: access violation reading 0xFFFFFFFFFFFFFFFF

**Comment by myhub** [comment]
pip install tr==2.6.7 -i https://pypi.tuna.tsinghua.edu.cn/simple 这个支持Windows了
