### ISSUE TITLE
    line_num = _libc.tr_run( OSError: [WinError -529697949] Windows Error 0xe06d7363 这个错误怎么解决？

### ISSUE THREAD

**Issue by nissansz** [myhub/tr#153]
这个错误怎么解决？

tr-2.3.0\tr\tr.py", line 229, in run
    line_num = _libc.tr_run(
OSError: [WinError -529697949] Windows Error 0xe06d7363

**Comment by myhub** [comment]
windows支持计划在后续版本支持
