### ISSUE TITLE
什么时候加入弯曲文本识别

### ISSUE THREAD

**Issue by ChenCong7375** [myhub/tr#158]
对于弯曲文本的识别效果一般，考虑进行弯曲文本识别开发吗

**Comment by myhub** [comment]
pip install tr==2.6.7 -i https://pypi.tuna.tsinghua.edu.cn/simple 新版本可以试试，对弯曲的估计好点

**Comment by myhub** [comment]
https://gitee.com/microic/tr/tree/master/crnn_for_text_with_multiple_lines
