### ISSUE TITLE
空格检测

### ISSUE THREAD

**Issue by shr1219** [myhub/tr#166]
同一个红色框内的文字间的空格会被忽略，有可能进行检测和保留吗

**Comment by myhub** [comment]
中文之间的空格目前是忽略的，主要是中文有全角字符和半角字符，如果不忽略会有歧义
用户可以自己根据blank符号的长度来判断中文文本行之间的空格

**Comment by shr1219** [comment]
> 中文之间的空格目前是忽略的，主要是中文有全角字符和半角字符，如果不忽略会有歧义 用户可以自己根据blank符号的长度来判断中文文本行之间的空格

怎么获得blank符号的长度呢，调用run函数直接就给出了最后结果

**Comment by myhub** [comment]
看了下2.3版本确实在C++内部实现了，用户没法改，新版本倒是用户可以自己改Python的后处理代码

**Comment by shr1219** [comment]
> 看了下2.3版本确实在C++内部实现了，用户没法改，新版本倒是用户可以自己改Python的后处理代码

试了下2.3C++版本，line.png只能识别出"firefox"，是识别率本就不太理想还是我没用对？ 以及
const int flag,
void * rect_arr,
const int max_lines, 这三个参数不知该怎么设置

**Comment by shr1219** [comment]
> > 看了下2.3版本确实在C++内部实现了，用户没法改，新版本倒是用户可以自己改Python的后处理代码
> 
> 试了下2.3C++版本，line.png只能识别出"firefox"，是识别率本就不太理想还是我没用对？ 以及 const int flag, void * rect_arr, const int max_lines, 这三个参数不知该怎么设置
好像是能识别出来的，只是输出模式有点问题没打印出来。是否unicode[w]中-1值的连续长度就为空格判断的标准？
此外还是请教下const int flag, void * rect_arr, const int max_lines要怎么配置，进不进行detect的区别在哪

**Comment by myhub** [comment]
> 是否unicode[w]中-1值的连续长度就为空格判断的标准？ 此外还是请教下const int flag, void * rect_arr, const int max_lines要怎么配置，进不进行detect的区别在哪

对，我说的就是根据unicode中-1的长度来判断是否是空白（空白不等于空格），因为都是用的CTCLoss，如果连续多个-1就基本可以确定是空白，flag我记得是可以设置是否支持带旋转角度的文本行
