### ISSUE TITLE
多行文本识别问题

### ISSUE THREAD

**Issue by Sqrt5** [myhub/tr#167]
请问如何确定文本行数呢？如果文本行数比较多，最后用ctc loss回归的时候，图像的宽度对应的帧数是不是会不够用，怎么解决这个问题呢？

**Comment by myhub** [comment]
输入灰度图像B 1 H W经过CNN提取特征后得到B C H//16  W//16，torch.permute成B H//16  W//16 C，再 reshape成B H*W//256 C，这样2D的图像就变成1D的了，后面的部分和CRNN一致

**Comment by Sqrt5** [comment]
那如果对于弯曲文字的话，如果弯的过大的话，那输出的顺序是不是就会有点问题了

**Comment by myhub** [comment]
感觉不会的，加了Transformer学习全局上下文的，我目前测试图片旋转15度，字体大小随机取14  ~72之间，输出的顺序也没错的。

**Comment by myhub** [comment]
![test7](https://github.com/myhub/tr/assets/43366542/ecfb6990-0931-4ee1-b765-31495c8ba135)
测试了一下，类似上面这样弯曲程度的文本可以很快学习出来
