### ISSUE TITLE
AttributeError: module 'tr' has no attribute 'recognize'

### ISSUE THREAD

**Issue by adzhua** [myhub/tr#171]
直接pip install tr安装的是2.8.6版本
然后运行
import tr
tr.recognize("imgs/line.png")
报AttributeError: module 'tr' has no attribute 'recognize'错误，请问这个怎么解决？

**Comment by myhub** [comment]
![图片](https://github.com/myhub/tr/assets/43366542/96190220-4a5e-41f0-82b2-840e4fe6d94a)
新版本是这么用的

**Comment by adzhua** [comment]
看到了，谢了
