### ISSUE TITLE
内存泄漏问题

### ISSUE THREAD

**Issue by light1003** [myhub/tr#18]
内存泄漏严重，看不到C++代码，猜测疑似问题为，ctypes没有释放内存，C++中要增加free函数，在C++端返回结果给python后由python主动调用free，释放之前C++的结构体。

**Comment by myhub** [comment]
谢谢，这个bug正在修改，应该是Opencv Mat没有release

**Comment by myhub** [comment]
@light1003 已经修复了，如果还有问题回复此issue
