### ISSUE TITLE
麻烦问一下，我tr.recognize识别出来的为空，tr.run正常工作,但我只需要识别出文本，请问tr.run可以只打印文本吗？我识别的图片如下

### ISSUE THREAD

**Issue by wangguanhua** [myhub/tr#20]
![1](https://user-images.githubusercontent.com/25172472/69724056-fcd60c00-1155-11ea-86b7-3c1af371e6de.png)

**Comment by myhub** [comment]
tr.recognize是识别单行文本用的

不需要要置信度、位置信息的话用下面的代码
`rect_arr = tr.run("test.jpg")

    for b in rect_arr:
        print(b[1])`

**Comment by wangguanhua** [comment]
好的，多谢你了

**Comment by wangguanhua** [comment]
> tr.recognize是识别单行文本用的
> 
> 不需要置信度、位置信息的话用下面的代码
> 
> rect_arr = tr.run("test.jpg")
> 
> for b in rect_arr:
>     print(b[1])

成功输出文本内容，但时间有些异常，跑了10分钟才出结果

**Comment by myhub** [comment]
这也太慢了吧
