### ISSUE TITLE
麻烦问一下大佬，我看您之前回复的说您的模型是移除了lstm，添加了resnet，那您是把ctbn中vgg+bilstm改为了vgg+resnet吗？

### ISSUE THREAD

**Issue by wangguanhua** [myhub/tr#21]

**Comment by myhub** [comment]
这个模型我后面有计划开源的，开源后你就知道了

**Comment by wangguanhua** [comment]
好的（主要是我毕设是做ocr的，但我的ctpn+crnn的模型再怎么训练准确率也没大佬你的高，所以好奇的问一下）

**Comment by myhub** [comment]
应该只是 训练集的 问题，跟模型几乎没关系
标准的CRNN我测试过，效果就很好，我现在用的模型是标准CRNN裁剪过的，为了减少模型的尺寸，效果应该还不如标准CRNN

**Comment by wangguanhua** [comment]
![对比前](https://user-images.githubusercontent.com/25172472/69781571-8f73bb00-11e9-11ea-919c-673168e2b58c.png)
![对比后](https://user-images.githubusercontent.com/25172472/69781585-969ac900-11e9-11ea-9226-6761140e7445.png)
第一张是我用标准模型识别的，第二张是用您的，可以明显看出识别率比不过您的。那照您这么说的确可能是我训练集不够大。但相应的，为什么您的模型识别时间会那么长呢，同一张图片我这边可能一分钟，您的模型可能就要10分钟

**Comment by myhub** [comment]
时间不好比的，你把你的模型用CPU libtorch部署后，估计速度也就慢了

**Comment by wangguanhua** [comment]
好的，麻烦您了。
