### ISSUE TITLE
大佬能否提供一下识别算法的详细流程，能否开源一下识别算法？

### ISSUE THREAD

**Issue by dun933** [myhub/tr#24]

**Comment by dun933** [comment]
测试发现识别的精度非常高，而且能识别长文本，希望大佬能提供一下算法的详细处理流程，或者提供论文链接，十分感谢。

**Comment by myhub** [comment]
算法就是普通的CRNN，没什么特别的。CRNN的开源代码很多

**Comment by dun933** [comment]
是CRNN+CTC的方式，还是 CRNN+attention的方式？训练样本的生成能否提供一些经验，十分感谢！

**Comment by myhub** [comment]
这个项目不适合研究或学习的，只适合在实际项目中使用

**Comment by dun933** [comment]
好的，感谢！
