### ISSUE TITLE
tr.run() function not working 

### ISSUE THREAD

**Issue by dg0975** [myhub/tr#25]
After run open thread in python tr.run() function geting error like

"terminate called after throwing an instance of 'c10::Error'
  what():  result.scalar_type() == iter.output().dtype() INTERNAL ASSERT FAILED at /pytorch/aten/src/ATen/native/BinaryOps.cpp:34, please report a bug to PyTorch.  (add_out at /pytorch/aten/src/ATen/native/BinaryOps.cpp:34)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7fb839d70813 in /home/deepak/.virtualenvs/cmt_new/lib/python3.6/site-packages/tr-1.3.0-py3.6.egg/tr/../libtorch/lib/libc10.so)
frame #1: at::native::add_out(at::Tensor&, at::Tensor const&, at::Tensor const&, c10::Scalar) + 0x29c (0x7fb7d2c48b8c in /home/deepak/.virtualenvs/cmt_new/lib/python3.6/site-packages/tr-1.3.0-py3.6.egg/tr/../libtorch/lib/libtorch.so)
frame #2: <unknown function> + 0xf79c3d (0x7fb7d309dc3d in /home/deepak/.virtualenvs/cmt_new/lib/python3.6/site-packages/tr-1.3.0-py3.6.egg/tr/../libtorch/lib/libtorch.so)
frame #3: <unknown function> + 0x2c9d366 (0x7fb7d4dc1366 in /home/deepak/.virtualenvs/cmt_new/lib/python3.6/site-packages/tr-1.3.0-py3.6.egg/tr/../libtorch/lib/libtorch.so)
frame #4: <unknown function> + 0x86e0a (0x7fb83a01be0a in /home/deepak/.virtualenvs/cmt_new/lib/python3.6/site-packages/tr-1.3.0-py3.6.egg/tr/libtr.so)
frame #5: at::Tensor::add_(at::Tensor const&, c10::Scalar) const + 0x10b (0x7fb83a01c11b in /home/deepak/.virtualenvs/cmt_new/lib/python3.6/site-packages/tr-1.3.0-py3.6.egg/tr/libtr.so)
frame #6: <unknown function> + 0x8d8a5 (0x7fb83a0228a5 in /home/deepak/.virtualenvs/cmt_new/lib/python3.6/site-packages/tr-1.3.0-py3.6.egg/tr/libtr.so)
frame #7: tr_detect + 0x1d8 (0x7fb83a00abb8 in /home/deepak/.virtualenvs/cmt_new/lib/python3.6/site-packages/tr-1.3.0-py3.6.egg/tr/libtr.so)
frame #8: ffi_call_unix64 + 0x4c (0x7fb8943e1dae in /usr/lib/x86_64-linux-gnu/libffi.so.6)
frame #9: ffi_call + 0x22f (0x7fb8943e171f in /usr/lib/x86_64-linux-gnu/libffi.so.6)
frame #10: _ctypes_callproc + 0x2b4 (0x7fb8945f55c4 in /home/deepak/.virtualenvs/cmt_new/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so)
frame #11: <unknown function> + 0x11d54 (0x7fb8945f5d54 in /home/deepak/.virtualenvs/cmt_new/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>
frame #13: python3() [0x509ad3]
frame #15: python3() [0x507125]
frame #16: python3() [0x508fa0]
frame #17: python3() [0x50999d]
frame #19: python3() [0x507125]
frame #20: python3() [0x508fa0]
frame #21: python3() [0x50999d]
frame #23: python3() [0x508c69]
frame #24: python3() [0x50999d]
frame #26: python3() [0x508c69]
frame #27: python3() [0x50999d]
frame #29: python3() [0x508c69]
frame #30: python3() [0x50999d]
frame #32: python3() [0x508c69]
frame #33: python3() [0x50999d]
frame #35: python3() [0x507125]
frame #36: python3() [0x5881aa]
frame #39: python3() [0x508c69]
frame #40: python3() [0x50999d]
frame #42: python3() [0x508c69]
frame #43: python3() [0x50999d]
frame #46: python3() [0x5940d1]
frame #48: python3() [0x5e09f2]
frame #49: python3() [0x631584]
frame #50: <unknown function> + 0x76db (0x7fb8980746db in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #51: clone + 0x3f (0x7fb8983ad88f in /lib/x86_64-linux-gnu/libc.so.6)
"

**Comment by myhub** [comment]
tr.run() is not thread-safe

**Comment by dg0975** [comment]
what should i do? if  I want a text recognise function for my project? and have bulk amount of data and the only solution is threading?

**Comment by myhub** [comment]
deep learning takes a great amount of CPU/RAM, so it is not a good idea to run many threads for text recognization. 

in most case, only 3 or 4 instances is allowed, so it is only possible to recognise 3 or 4 text images at the same time

so queue is often used, the tasks need to queue until former tasks are finished

**Comment by dg0975** [comment]
Yeah, you are right, but run() function does not even work in 2 threads open.

**Comment by myhub** [comment]
Yes, to make the API as simple as possible, I disable the session which make the API is not thread-safe

**Comment by dg0975** [comment]
can you help me out for this problem solution?

**Comment by myhub** [comment]
I need to work at daytime, part-time job at weekend.
when I am not busy, I will help

**Comment by dg0975** [comment]
Thank you for helping hand
