### ISSUE TITLE
求作者一个好友位

### ISSUE THREAD

**Issue by nowbug** [myhub/tr#28]
非常感谢作者开发的这个框架，它解决了我毕设的90%的问题，另外我支持作者免费的很难将ocr做的更好，我愿意为此付费，能不能给个联系方式。我的邮箱是xuluda@163.com，如有打扰请多多担待。

**Comment by lzmisscc** [comment]
你要做的是什么毕设？

**Comment by myhub** [comment]
> 非常感谢作者开发的这个框架，它解决了我毕设的90%的问题，另外我支持作者免费的很难将ocr做的更好，我愿意为此付费，能不能给个联系方式。我的邮箱是[xuluda@163.com](mailto:xuluda@163.com)，如有打扰请多多担待。

部分C++代码未开源，不好意思接受捐款

**Comment by nowbug** [comment]
> > 非常感谢作者开发的这个框架，它解决了我毕设的90%的问题，另外我支持作者免费的很难将ocr做的更好，我愿意为此付费，能不能给个联系方式。我的邮箱是[xuluda@163.com](mailto:xuluda@163.com)，如有打扰请多多担待。
> 
> 部分C++代码未开源，不好意思接受捐款

我不需要C++代码开源，不要训练数据，有个问题想咨询一下作者，我意思愿意为问答知识付费。这仅仅是我一点点心意。我的邮箱是xuluda@163.com，期待获得您的联系方式。不会太耽误您的时间。

**Comment by myhub** [comment]
给你发邮件了
