### ISSUE TITLE
如何使用c++接口？

### ISSUE THREAD

**Issue by zhangqizky** [myhub/tr#29]
请问楼主能给一下libtr.so的接口说明嘛？想用c++去调...要做一个完整的项目，因为检测到文本框之后对文本框的处理是c++写的，谢谢！

**Comment by myhub** [comment]
目前就只有一个简单的API文档
https://github.com/myhub/tr/wiki/C-API

**Comment by zhangqizky** [comment]
好嘞，我研究研究

**Comment by Whu-wxy** [comment]
@zhangqizky 请问可以使用吗？这里不是没有给出头文件么

**Comment by myhub** [comment]
新版本C++调用好简单的。
