### ISSUE TITLE
coding with something unexpect

### ISSUE THREAD

**Issue by light1003** [myhub/tr#3]
I run your example code ,got this,I get error when try to encode with utf8 or unicode ,which code format do you use?
('\xe8\xb2\xa1\xbe\xe8\xbb\xe6\xe6\x94\x96\x83\xe6\xe9\x84\x87\xe5\xe9\xbf\xe7\xb3\xbc\x87\x88\xe8\x8f\x84\x9f\xa7', 0.9915148339101246)
[((554, 112, 117, 51), '\x9a\x88', 0.9467410445213318), ((305, 180, 93, 20), '\xe4\x82\x9c\xe4', 0.9151563346385956), ((412, 180, 330, 24), '\xe4\x82\x9c\xe4\xb4\x88\xe7\xe7\xb6\xb5\xe5\xe7\xba\xe9', 0.9632651607195536), ((413, 208, 156, 20), '\xae\xe5\xe4\xb6\x82\xba\xe9', 0.9853425877434867), ((413, 233, 27, 20), '\xae', 0.9998985528945923), ((457, 234, 158, 19), '\x9d\xe7\xae\xe5\xe5\x9c\x84\xe4\xb4\xa8\xba\xe9', 0.991575633486112), ((413, 249, 75, 19), '\xe7\x92\xe5\x9b\xe7', 0.9989503979682922), ((590, 249, 61, 19), '\xe7\x92\xe6\xe6\xe7', 0.9982295155525207), ((413, 264, 27, 19), '\xe8', 0.9997397065162659), ((458, 264, 30, 19), '\xb8\xe7', 0.9998543560504913), ((590, 264, 45, 18), '\x85\xbd\xe7', 0.9461611956357956), ((414, 280, 59, 17), '\xbf\xbf\x84\xb2\x8b\xe7', 0.9946015079816183), ((460, 412, 130, 28), '\xe5\xa5\x8b\x8c\x9c\x81', 0.9867955446243286), ((318, 447, 113, 24), '\xb8\xa7\xe8\xe7\xe7\xe8', 0.9994733134905497), ((438, 447, 143, 24), '\xba\x8c\xb4\x88\xe7\xe7\xe8', 0.999678339276995), ((577, 449, 134, 21), '\xe8\xe5\xb4\x88\xe7\xe7\xe8', 0.9630055257252285), ((298, 469, 94, 24), '\x89\x87\xe7\xe7\xe8', 0.9995172381401062), ((398, 469, 106, 24), '|\xa4\xe7\xe7\xe8', 0.9996068954467774), ((497, 469, 103, 24), '\xe7\xe5\xe7\xe7\xe8', 0.9994497537612915), ((598, 469, 141, 24), '\xe8\x83\x94\x91\xe7\xe7\xe8', 0.999497047492436), ((338, 491, 95, 24), '\xe7\xe9\xe7\xe7\xe8', 0.9988212585449219), ((438, 491, 187, 24), '\x9c\xb1\xb4\xb9\xe8\xe5\xe7\xe7\xe8', 0.9731513659159342), ((616, 491, 94, 24), '\xe5\xa4\xe7\xe7', 0.9993427693843842), ((420, 494, 19, 19), '\xe8', 0.9990966320037842), ((366, 537, 141, 21), '\xa5\xa6\xae\xe5\xb3\xe4\x82\xa6', 0.9991673827171326), ((294, 537, 33, 24), '\x89', 0.9992363452911377), ((326, 538, 43, 20), '\x9a\x88', 0.9994674324989319), ((497, 538, 173, 19), '\xba\x85\x85\x85\xbb\xe5\x85\xe8\xbf\x85\x85\xef\x85\x85\x85\xe5\x85\xbb\xba', 0.9999961413835224), ((294, 554, 32, 21), '\xe5', 0.9939039349555969), ((327, 562, 40, 21), '\x9a\x88', 0.9996269643306732), ((367, 562, 219, 21), '\x88\xa6\xae\xe5\xb3\x90\x82\xa6\xe4\xe5\x8d\x97\xb0', 0.9996723670225877), ((578, 563, 169, 19), '\xba\x85\x85\xbb\xe8\xbb\xe5\xa8\xe6\x85\xe6\xa8\x85\xbb\xe8\xba\x85\x85\x85', 0.999539127475337), ((294, 566, 32, 24), '\xbd', 0.9983735084533691), ((294, 584, 31, 20), '\x8f', 0.9987269043922424), ((326, 587, 43, 20), '\x9a\x88', 0.9995181262493134), ((368, 587, 109, 20), '\x89\xa6\xae\xe5\x8d\xa6', 0.9997077683607737), ((468, 588, 169, 19), '\x85\x85\x85\x85\xe5\x85\x85\xe5\xe5\x85\x85\xe5\xba\xa8\xa8\xef\xe6\xbb\xef', 0.9999455464513678), ((3, 727, 86, 26), '\xa6\x87-', 0.7006986737251282), ((78, 729, 156, 25), '\xe9\xe9\xe9\xe7\x87\xb2\xe9\xb2\xe9\xe7\xbe\xbb\xbf', 0.9132847625475663), ((685, 733, 337, 20), '\xe7\x87\xae\x96\xa3\x83\x9d\x90\x9f\xe5\xe7\x85\xe5\x85\xe8\xe5\xe6\xe5\xbb\x85\xbb\xe8\xa8\x85\x85\xe6\x85\xbb\x85\xef\x85', 0.9431320652365685)]

**Comment by myhub** [comment]
We use utf-8
The output is already str, and there is no need to encode

**Comment by light1003** [comment]
> We use utf-8
> The output is already str, and there is no need to encode

but I run your code ,get error result,such as your demo draw result will be something unkonw,
![test](https://user-images.githubusercontent.com/18361387/64418501-b8465180-d0cd-11e9-995e-e7fc6d91bff8.jpg)
could you help me？where I make false？

**Comment by light1003** [comment]
python 2.7,directly run your test.py and only modified the last line as "blank_pil.save("test.jpg")" to save this image

**Comment by myhub** [comment]
> python 2.7,directly run your test.py and only modified the last line as "blank_pil.save("test.jpg")" to save this image

I have not tested under python 2.7, all code is tested under Python 3.6

**Comment by light1003** [comment]
thank you for your help ,changing py3 has some error too,using PYTHONIOENCODING=utf-8 at first will be ok
