### ISSUE TITLE
Request for windows version of module

### ISSUE THREAD

**Issue by pankajusic2008** [myhub/tr#31]
Dear Team,

Request you to please upload the windows version of the same. I am trying to use the same on windows machine.
The module was getting installed properly but raising an error during import statement.
![image](https://user-images.githubusercontent.com/37615417/73091160-d4715080-3eff-11ea-8d33-897e0ec3919c.png)

![image](https://user-images.githubusercontent.com/37615417/73091209-f23eb580-3eff-11ea-8dce-3b70c260817e.png)

[log.txt](https://github.com/myhub/tr/files/4109859/log.txt)

![image](https://user-images.githubusercontent.com/37615417/73091473-8577eb00-3f00-11ea-81db-c57ad89f905b.png)

Request your support on the same.

Thanks in advnce.

Thanks
Pankaj Gupta

**Comment by myhub** [comment]
I found some bug of libtorch on windows which I can not solve, so I do not upload windows version.

**Comment by myhub** [comment]
New version support Windows now
