### ISSUE TITLE
MacOS: python test.py 错误

### ISSUE THREAD

**Issue by ademolyk** [myhub/tr#32]
<img width="1145" alt="error" src="https://user-images.githubusercontent.com/42731232/74115100-6f4c7900-4be8-11ea-8d1e-5213fd0337c5.png">

貌似打不开libtr.so的文件。

**Comment by ademolyk** [comment]
@myhub

**Comment by myhub** [comment]
macOS 跟 linux不兼容

**Comment by ademolyk** [comment]
> macOS跟linux不兼容
那个sdk 只能在linux下跑吗？

**Comment by ademolyk** [comment]
谢谢，已在linux上跑通。

**Comment by wispytrace** [comment]
> 谢谢，已在linux上跑通。
想请问怎么跑通的鸭,我试了16.04 18.04,在ubuntu上都还是报了libtr.so的错误,还是OSError: cored dumped

**Comment by myhub** [comment]
ubuntu 16.04下测试过的，应该没问题。如果问题依然解决不了，可以开个新Issue，附上安装过程，测试用的命令，以及错误的截图
