### ISSUE TITLE
Ram Spiking while using this code

### ISSUE THREAD

**Issue by sriichandana** [myhub/tr#34]
while using this code my system ram is spiking and if i process with multiple images my system was hanging, and after completion of process also Ram usage not coming to normal stage and then it will effecting for the next process, i am using 16GB RAM , graphic card system let me know how I can resolve it

**Comment by myhub** [comment]
I plan to use OnnxRuntime to rewrite the code
Currently this code is not thread-safe

**Comment by sriichandana** [comment]
When I can expect the updated code?

**Comment by myhub** [comment]
I am not sure. Currently I have another project to do, so I spend less time on OCR.

**Comment by myhub** [comment]
I am not sure. Currently I have another project to do, so I spend less time on OCR.

**Comment by myhub** [comment]
v2.0 updated
