### ISSUE TITLE
可以告知一下训练数据吗

### ISSUE THREAD

**Issue by courao** [myhub/tr#36]
体验了一下，识别效果不错
想问问这是用公开的或者生成的数据训练的吗，
如果是内部数据不便透露的话可否告知数据量大概要多少？

**Comment by hannixu** [comment]
您好，请问您关注的是哪个项目呢？我怎么看不到项目相关的信息呢？



hanni_xu@126.com
 
发件人： 唐董琦
发送时间： 2020-03-12 01:55
收件人： myhub/tr
抄送： Subscribed
主题： [myhub/tr] 可以告知一下训练数据吗 (#36)
体验了一下，识别效果不错
想问问这是用公开的或者生成的数据训练的吗，
如果是内部数据不便透露的话可否告知数据量大概要多少？

**Comment by courao** [comment]
@hannixu 文字检测和识别的算法还挺多的，其中大部分都时开源的，文字检测的CTPN/EAST/PixelLink/PSENet文字识别CRNN，都可以在GitHub上找到。
从其他issue看识别用的算法似乎时CRNN，检测的具体算法不太清楚不过应该也是公开的算法，
但是因为受限于训练数据的原因，很多算法实际用的时候鲁棒性不太高，
所以想问问po主用的啥数据。。。

**Comment by myhub** [comment]
样本无非就是3种来源 
1、自己合成 占比30%以上
2、网上收集 占比30%左右
3、人工标注后再数据增强 占比尽量大
总体样本规模1000万，不做数据增强的话，原始的样本大概是100万

**Comment by courao** [comment]
好的，非常感谢！
