### ISSUE TITLE
请问大佬，此项目有没有内置的次数或时间限制？超过多少就不能用了

### ISSUE THREAD

**Issue by beeper00** [myhub/tr#39]
大佬，之前我使用1.3版本的，用着用着突然不能用了。
本来用了几个月都没事，突然报错说是 核心已转储，然后我把之前下好的zip包考到服务器上，也报这个错，不知何故。来github重新下了1.5版本才解决。
请问大佬，此项目有没有内置的次数或时间限制？超过多少就不能用了?

**Comment by myhub** [comment]
稳定版本无任何限制的

**Comment by beeper00** [comment]
多谢
