### ISSUE TITLE
segmentaion fault(core dumped)

### ISSUE THREAD

**Issue by chenyangjun45** [myhub/tr#40]
2019年11月15日左右下代码，运行test.py成功，放进docker里一直使用正常，最近开始报"segmentaion fault(core dumped)"这个错，是什么原因

**Comment by chenyangjun45** [comment]
我这边环境没问题，因为之前把运行成功的环境放进docker了

**Comment by myhub** [comment]
不要用测试版本，测试版本有时间限制的
目前稳定版本是1.5，无限制
