### ISSUE TITLE
不能和GPU一起跑么

### ISSUE THREAD

**Issue by zhouguanghui001** [myhub/tr#41]
我自己建立一个文本检测模型，然后调用tr识别，会报错。但单独跑没问题

**Comment by myhub** [comment]
不支持GPU的，跟pytorch一起跑的话可能会冲突，因为tr也用了不同版本的libtorch

**Comment by zhouguanghui001** [comment]
可以跟tensorflow一起跑了？我怕换了以后还会有问题。

**Comment by zhouguanghui001** [comment]
@myhub 可以跟tensorflow一起跑了？我怕换了以后还会有问题。

**Comment by myhub** [comment]
新版本支持GPU了
