### ISSUE TITLE
问一下关于速度的问题

### ISSUE THREAD

**Issue by beeper00** [myhub/tr#42]
使用时我发现，首次使用或间断使用时速度很慢，大约5s左右才能出结果。而使用for循环连续识别则很快，都能在0.2s以下。
已确认没有在我的python代码中反复加载模型之类，请问这是什么原因？是不是我的使用方法不对造成的？有没有解决办法呢？

**Comment by myhub** [comment]
tr_init只需要执行一遍的

**Comment by whuhit** [comment]
你好，请问下怎么用的呢，我用for循环每张照片时间都差不多也都是5秒呢

**Comment by myhub** [comment]
tr 2.0 is updated, more faster, more simple
