### ISSUE TITLE
请教下速度问题

### ISSUE THREAD

**Issue by whuhit** [myhub/tr#44]
特别感谢作者的开源项目，准确率挺高的。我在使用的时候遇到了一些问题，就是这个项目挺吃内存和cpu的，性能差点的机器可能都无法启动，另外就是我用都时候速度特别慢，每张图像大概在5秒左右。不知道是不是我用的不对还是怎么的，恳请作者看到答复一下

**Comment by myhub** [comment]
速度确实不怎么样，也没太多的时间去优化，虽然有计划用Onnxruntime重新改写，估计CPU下速度能从5s优化到1s以内，不过还是时间问题

**Comment by whuhit** [comment]
> 速度确实不怎么样，也没太多的时间去优化，虽然有计划用Onnxruntime重新改写，估计CPU下速度能从5s优化到1s以内，不过还是时间问题

我在另一个issue里看到有人说使用for循环连续识别则很快，第二张图片及以后都能在0.2s以下。这个是我用法不对么，我后面图片速度也还是跟第一张一样呢

**Comment by myhub** [comment]
如果输入图片很小，0.2s是可以
输入图片越大，耗时越大

**Comment by myhub** [comment]
tr 2.0 is updated, more faster, more simple
