### ISSUE TITLE
想问下文本检测用的什么算法？

### ISSUE THREAD

**Issue by Wangjii** [myhub/tr#48]
po主，这效果也太棒了，从其他Issue得知识别部分用的CRNN，不知检测部分用的什么算法？有开源计划不？？

**Comment by myhub** [comment]
用PixelLink做文本检测

**Comment by Joyako** [comment]
@myhub 你用什么数据集啊，是自己生成的吗

**Comment by rsqai** [comment]
看了下应该是CTPN把，tr里有CTPN的bin文件，这个要是再能加一个角度检测模型，效果就非常棒了，目前超过20度倾斜的文本识别效果不是很好~~

**Comment by nissansz** [comment]
> @myhub 你用什么数据集啊，是自己生成的吗

您好，怎样可以用的日文的crnn.bin文件？微信nlanguage
