### ISSUE TITLE
图片识别速度慢

### ISSUE THREAD

**Issue by wangguanhua** [myhub/tr#49]
您好，上一个版本我一张图片需要用十分钟才能识别出来，这个版本耗费时间也差不多，请问我需要怎样处理能够使识别速度快一些呢？图片格式如下所示
![4](https://user-images.githubusercontent.com/25172472/80352571-a73d9100-88a6-11ea-8389-fba3be328350.png)

**Comment by myhub** [comment]
之前版本使用的是libtorch，libtorch本身速度比较慢，还有文本行是一行一行执行的，文本行越多，速度越慢。如果改改程序让多个文本行一起识别，会快很多倍，这个开发比较难，理论上你上面的图片在CPU下2s左右可是完成检测和识别的

**Comment by wangguanhua** [comment]
我很好奇为什么您的模型会执行的这么慢，因为我把图片送入我自己训练的CRNN+CTPN中基本秒出结果（正确率比起您的差远了）。您imgs文件夹中name_card.jpg也是，一分多钟才出结果

**Comment by myhub** [comment]
当时做的时候为了简单，就用了pytorch的libtorch，没想到这么慢
网络本身已经做了精简，比CTPN和标准CRNN快

**Comment by wangguanhua** [comment]
不应该啊，现在工业界也有用libtorch去部署的，我之前用别的libtorch也没有这种情况出现，毕竟您刚也说了要比CTPN\CRNN快。

**Comment by myhub** [comment]
我这边部署没经验，所以慢
也可能是模型设计的很差，所以模型本身就慢

**Comment by wangguanhua** [comment]
大佬您谦虚了，您的模型在识别正确率上是最好的，百度及腾讯的ocr在正确率上都比不过您模型的结果

**Comment by myhub** [comment]
多谢肯定，后面有计划使用OnnxRuntime优化速度的

**Comment by deep-practice** [comment]
@wangguanhua 您是在多大的测试集上面得出的结论？

**Comment by wangguanhua** [comment]
> @wangguanhua 您是在多大的测试集上面得出的结论？

就上面的那张测试图片啊

**Comment by myhub** [comment]
据说libtorch 1.5.0速度快了很多倍，有空我试试

**Comment by myhub** [comment]
tr 2.0 is updated, more faster, more simple
