### ISSUE TITLE
能设置使用GPU吗？

### ISSUE THREAD

**Issue by aisegment** [myhub/tr#5]
能设置使用GPU吗？

**Comment by myhub** [comment]
使用GPU需要使用libtorch的GPU版本，同时代码要做轻微的修改，由于libtorch GPU包文件很大，所以无法上传到github，估计会上传到百度网盘之类的。

支持GPU在TODO list里面，不过优先级排列的比较靠后，优先级从高到低依次为
+ 识别部分支持带角度的文本框
+ 优化识别部分代码，当前文本识别准确率不够高
+ 支持Windows/Mac OS等操作系统
+ 支持表格检测
+ 识别英文空格
+ 支持GPU/手机端

**Comment by deep-practice** [comment]
良心开源，大佬能分享一下关于数据生成的经验么

**Comment by myhub** [comment]
> 良心开源，大佬能分享一下关于数据生成的经验么

Python部分代码都开源了，希望可以帮到大家

感觉数据生成没什么技术难度吧，就是超级枯燥，需要很长的时间，无非就是平移、旋转、模糊、透视、噪声等等操作的组合，开源的代码很多，论文也不少，很多真实效果是很难合成的，最后还是只能人工标定

**Comment by deep-practice** [comment]
当图像质量不好的时候，就容易认成跟当前字符形近的字。。

**Comment by myhub** [comment]
恩，识别部分还要优化，在TODO列表里，优先级最高

**Comment by lzmisscc** [comment]
请问如何设置，相关的代码能上传到网盘吗？谢谢！

**Comment by myhub** [comment]
暂时不计划支持GPU
