### ISSUE TITLE
大佬，多线程问题可否解决下，想用做后台，并发量有点大，不支持多线程恐怕不行

### ISSUE THREAD

**Issue by DYJYZP** [myhub/tr#52]
我用的是java调用python脚本的方式来弄的，发现多线程调用会出现卡死的情况，问问大佬可不可以改成支持多线程并发调用，这样才可能用到生产环境中

**Comment by myhub** [comment]
之前版本使用的是libtorch，不支持多线程，可能libtorch本身也有内存泄漏是我无法解决的
后面计划用onnxruntime，onnxruntime可以避免上面的问题

**Comment by DYJYZP** [comment]
> 之前版本使用的是libtorch，不支持多线程，可能libtorch本身也有内存泄漏是我无法解决的
> 后面计划用onnxruntime，onnxruntime可以避免上面的问题

也是在这个项目上写吗？如果不是，项目地址可以发下吗？谢谢！必将持续关注

**Comment by myhub** [comment]
依然是这个项目，计划了很久要切换到onnxruntime，就是最近工作实在太忙，有空了就做

**Comment by DYJYZP** [comment]
> 依然是这个项目，计划了很久要切换到onnxruntime，就是最近工作实在太忙，有空了就做

好的，谢谢答复

**Comment by myhub** [comment]
tr 2.0 is updated, more faster, more simple
