### ISSUE TITLE
期待大佬 解决内存泄漏 和多线程问题！

### ISSUE THREAD

**Issue by wangchuanlai** [myhub/tr#54]
怎么形容目前项目呢！！！就是像是一个食物非常好吃，但是吃起来就会造成便秘 那么让人爱恨交加。
现在的版本还无法投入到实际项目中，且内存泄漏造成的系统不稳定。

**Comment by myhub** [comment]
后面会暂停优化检测 识别精度，解决您提到的这些问题
包括速度优化问题

希望大家多多支持

**Comment by wangchuanlai** [comment]
再次感谢大佬！
