### ISSUE TITLE
如果打算开源的话，可不可以考虑把数据集和训练代码放出来，有些地方是不是故意做了模糊处理，车牌识别的时候不显示汉字

### ISSUE THREAD

**Issue by liaoweiguo** [myhub/tr#55]
如果打算开源的话，可不可以考虑把数据集和训练代码放出来，有些地方是不是故意做了模糊处理，车牌识别的时候不显示汉字

放出来的话我们可以试着做一个手机版本

**Comment by myhub** [comment]
你说的代码之前有客户付费购买过，数据集有部分也是客户提供的。按协议是不能放出去的，否则付费客户还会找我赔钱的

**Comment by ybdesire** [comment]
> 虽然是通用OCR，不过样本中没有车牌，无法保证对车牌识别的精度，没有什么模糊处理呀，就是网络输出什么就是什么。
> 
> 你说的代码之前有客户付费购买过，数据集有部分也是客户提供的。按协议是不能放出去的，否则付费客户还会找我赔钱的

请问该如何购买？ 请和我邮件练习，谢谢！ 

  chejin@mail.yuzaishi.cn
