### ISSUE TITLE
2个权重.bin文件是怎么生成的

### ISSUE THREAD

**Issue by ttyhu** [myhub/tr#58]
兄弟，问下啊，.bin的2个权重文件是怎么生成的

**Comment by myhub** [comment]
一个精简版的CRNN 一个精简版的CTPN
用pytorch训练的，bin就是导出后的权重

**Comment by ttyhu** [comment]
还真不知道pytorch可以导出成bin文件啊

**Comment by myhub** [comment]
就是bin文件仅仅只保留了权重信息

**Comment by ttyhu** [comment]
能指导下怎么做到保存成bin方式吗，和读取，我觉得这个部署环境很方便

**Comment by myhub** [comment]
这个就是每个权重参数存储成4个字节，所以参数按顺序存储

**Comment by ttyhu** [comment]
是不是把所有权重参数形状打散顺序排列保存在bin文件 然后图的信息放在so文件里

**Comment by ttyhu** [comment]
想和您请教些问题，可以的话1318xx4242xx65三，shanghai

**Comment by myhub** [comment]
是的 权重参数按顺序排列保存在bin文件

**Comment by myhub** [comment]
> 想和您请教些问题，可以的话1318xx4242xx65三，shanghai

我的邮箱是 anycode@yahoo.com，多交流
