### ISSUE TITLE
新版对倾斜文字的识别效果远差异于旧版

### ISSUE THREAD

**Issue by quuhua911** [myhub/tr#59]
![id_card](https://user-images.githubusercontent.com/35398080/82852737-5026ec80-9f36-11ea-9055-f570ae2ae172.jpeg)
旧版：imgs/id_card.jpeg 550 366
[((287.26123, 78.45596, 256, 39, -12.881977), '中华人民共和国', 0.9990006940705436), ((296.95483, 132.60115, 306, 51, -12.804266), '居民身份证', 0.9999288201332093), ((313.3752, 249.26889, 72, 23, -11.976132), '公安局', 0.9999696811040243), ((196.90588, 274.57648, 68, 23, -12.528809), '签发机关', 0.9965862035751343), ((367.96823, 274.35052, 136, 24, -11.996899), '3.14-2029.05.14', 0.9752597689628602), ((190.53848, 313.3077, 36, 21, -7.1250167), '有效', 0.9622694253921509)]

新版：# tr 1.5.0 https://github.com/myhub/tr
imgs/id_card.jpeg 550 366
0 φe人
1 gμ※θ※
2 多
3 公安局
4 鉴发机苯
5 携效

**Comment by myhub** [comment]
uc@DESKTOP-SYW:/mnt/c/Users/HGZN007/Desktop/OCR/1.5.1/tr$ python3 test_angle.py
# tr 1.5.0 https://github.com/myhub/tr
imgs/id_card.jpeg 550 366
0 中华人民共和国
1 居民身份证
2 公安局
3 签发机关
4 5.14-2029.05.14
5 有效

我刚测试了一下，这是新版的结果

**Comment by myhub** [comment]
python3 test_angle.py
tr 1.5.0 https://github.com/myhub/tr
imgs/id_card.jpeg 550 366
0 中华人民共和国
1 居民身份证
2 公安局
3 签发机关
4 5.14-2029.05.14
5 有效
我刚测试了一下，这是新版的结果

**Comment by quuhua911** [comment]
你是对的，我搞错了。
