### ISSUE TITLE
Why is the time running the same image not the same? I ran the same image but the time difference was 2 seconds

### ISSUE THREAD

**Issue by ducbluee** [myhub/tr#61]

**Comment by myhub** [comment]
The software is too CPU consuming, so the time depends heavily on the status of CPU
fi the CPU is doing other tasks, the time will be longer

**Comment by ducbluee** [comment]
> Phần mềm quá tốn CPU, vì vậy thời gian phụ thuộc rất nhiều vào trạng thái của CPU
> nếu CPU đang thực hiện các tác vụ khác, thời gian sẽ lâu hơn

Oh, so that's it. So is there any way to improve this situation?

**Comment by myhub** [comment]
I am developing a new version based on Onnxrutime which will have better speed
For even more faster, GPU version is suggested which is also under development

**Comment by ducbluee** [comment]
> I am developing a new version based on Onnxrutime which will have better speed
> For even more faster, GPU version is suggested which is also under development

thank, hopefully there will be a new version soon

**Comment by myhub** [comment]
tr 2.0 is updated, more faster, more simple

**Comment by ducbluee** [comment]
Thank authors

Vào Th 5, 4 thg 6, 2020 vào lúc 20:02 Dream <notifications@github.com> đã
viết:
