### ISSUE TITLE
新版本安装问题

### ISSUE THREAD

**Issue by wangguanhua** [myhub/tr#62]
您好，麻烦问一下，我之前是安装了老版本，新版本的安装不需要对老版本进行卸载什么的吗？

**Comment by myhub** [comment]
直接把tr复制到要运行tr的目录也行，有个setup. py我还没上传

**Comment by myhub** [comment]
新版本没有经过长期测试，建议保留旧版本，不用卸载

**Comment by wangguanhua** [comment]
保留老版本，您的意思是直接在tr文件夹里运行test.py进行安装吗？新老版本都是import tr，不会产生冲突吗

**Comment by myhub** [comment]
不会的。优先从当前目录导入tr的

**Comment by myhub** [comment]
不会的。优先从当前目录导入tr的

**Comment by wangguanhua** [comment]
安装新版本后无论是运行test-multi-thread.py还是自己的图像识别程序，总会出现Killed，从而结束程序

**Comment by myhub** [comment]
test-multi-thread.py是多线程测试，你说的问题如何复现
