### ISSUE TITLE
关于依赖库的问题

### ISSUE THREAD

**Issue by Qianftb** [myhub/tr#64]
tr1.0.3找不到，请问这个包是下架了吗？
Could not find a version that satisfies the requirement tr==1.0.0.3 (from -r requirements.txt (line 6)) (from versions: 0.0.1, 1.0.0.1, 1.0.0.2)

**Comment by myhub** [comment]
pip上没法上传60M以上的包。所以之前的1.0.0.3不完整的，就删除了

**Comment by Qianftb** [comment]
原来如此，那如果我要使用1.0.0.3的包，请问哪里可以找到呢？或者使用其他版本可以吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dream"<notifications@github.com&gt;; 
发送时间: 2020年6月5日(星期五) 下午2:16
收件人: "myhub/tr"<tr@noreply.github.com&gt;; 
抄送: "千帆"<1016577913@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [myhub/tr] 关于依赖库的问题 (#64)





 
pip上没法上传60M以上的包。所以之前的1.0.0.3不完整的，就删除了
