### ISSUE TITLE
windows 动态库

### ISSUE THREAD

**Issue by AIwzx** [myhub/tr#65]
大佬什么时候更新dll

**Comment by myhub** [comment]
免费项目不计划支持那么多平台的。除了Windows 目前还有苹果 ARM 等平台需要支持

**Comment by AIwzx** [comment]
哈哈 那也多谢大佬开源&nbsp; 想测试一下跟我训练的psenet性能&nbsp; 发现没有dll库


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dream"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月6日(星期六) 晚上7:05
收件人:&nbsp;"myhub/tr"<tr@noreply.github.com&gt;;
抄送:&nbsp;"兴"<1035459700@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [myhub/tr] windows 动态库 (#65)





 
免费项目不计划支持那么多平台的。除了Windows 目前还有苹果 ARM 等平台需要支持

**Comment by myhub** [comment]
windows下用wsl也可以运行linux程序的

**Comment by AIwzx** [comment]
多谢大佬提醒
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dream"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月6日(星期六) 晚上7:17
收件人:&nbsp;"myhub/tr"<tr@noreply.github.com&gt;;
抄送:&nbsp;"兴"<1035459700@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [myhub/tr] windows 动态库 (#65)





 
windows下用wsl也可以运行linux程序的

**Comment by myhub** [comment]
现在已经支持Windows系统了
