### ISSUE TITLE
OCR耗内存

### ISSUE THREAD

**Issue by aBlindBoy** [myhub/tr#7]
这个OCR很耗内存和CPU呢，我服务器16G的内存，而且识别完之后也没有回收内存，只能识别600kb以下的图片，识别1M以上的服务器会卡死，问下大佬怎么解决呢

**Comment by myhub** [comment]
是的，目前没有回收内存，当初的想法是为了在下一次识别时不用再重新申请内存，以加快速度

不过由于大部分场景下每次输入图片的尺寸都不一致，导致每次不得不重新申请内存，所以识别完成后立刻回收内存更合理，我这边会修改代码，修改为: 检测/识别完成后立刻回收内存，请关注代码更新

另外，内存消耗的多少应该只与图片的尺寸有关

**Comment by myhub** [comment]
代码已更新，如仍有问题请回复

**Comment by aBlindBoy** [comment]
好的，感谢大佬

**Comment by aBlindBoy** [comment]
![~color_pil](https://user-images.githubusercontent.com/44792248/65813057-465fb480-e202-11e9-911d-6a55a51645b0.png)
你好，这个红头文件的标题怎么可以识别出来，是红色字体就就识别不出来吗

**Comment by myhub** [comment]
不是的，网络对特别大的字体检测不到，需要把图片适当缩小点再检测
