### ISSUE TITLE
断开网络程序无法正常运行

### ISSUE THREAD

**Issue by pengzhouliangdao** [myhub/tr#70]
把网络连接断开，程序会报错。查了下应该是tr.py里面调用的libtr.so里面的初始化函数引起的崩溃，是不是libtr.so里面进行了网络连接？

**Comment by myhub** [comment]
是的，目前有个联网统计的功能

**Comment by pengzhouliangdao** [comment]
有没有接口能把这个联网统计的功能关闭掉？

**Comment by AIwzx** [comment]
会不会远程给关了

**Comment by myhub** [comment]
不会的。保证99.99%以上的可用性

**Comment by whuhit** [comment]
请问下，可以有办法断网情况下运行吗

**Comment by myhub** [comment]
2.2版本不行的，仅仅是初始化联网一下下
1.5版本的可以

**Comment by pengzhouliangdao** [comment]
Enough Information
