### ISSUE TITLE
请问大佬，部署在8核8G服务器上，每次是被cpu1000%以上，怎么办

### ISSUE THREAD

**Issue by zuiyuewentian** [myhub/tr#75]
请问大佬，部署在8核8G服务器上，每次是被cpu1000%以上，怎么办

**Comment by myhub** [comment]
感觉可以用Docker做资源限制，或者限制openmp的核心数
限制openmp好像可以修改环境变量实现

**Comment by zhongguohun** [comment]
> 感觉可以用Docker做资源限制，或者限制openmp的最大线程数
> 限制openmp好像可以修改环境变量实现

闭源的部分代码可以购买吗

**Comment by myhub** [comment]
技术合作的话，可以邮件哦： anycode@yahoo.com
