### ISSUE TITLE
新版报错

### ISSUE THREAD

**Issue by wangguanhua** [myhub/tr#76]
运行test.py,输出
recognize ('FireFox浏览器(Quantum),截图功能百度经验', 0.9988267783607755)
time 0.10659360885620117
0        中华人民共和国 0.9602746739983559
1         0.0
2        居民身份证 0.9998735427856446
3        签发机关 0.9169837981462479
4        公安局 0.9999551375706991
5        有效 0.8230864703655243
6        5.14-2029.05.14 0.9484508901834487
(ocr) www@Teacher-Fish:~/tr$ display: unable to open X server `' @ error/display.c/DisplayImageCommand/426.

**Comment by myhub** [comment]
这个不是错误。可以注释掉显示图片的哪行

**Comment by wangguanhua** [comment]
好的，多谢
