### ISSUE TITLE
increase the accuracy of ctpn

### ISSUE THREAD

**Issue by ducbluee** [myhub/tr#77]
for detect Chinese words, it is missing the last word in the line

**Comment by myhub** [comment]
thanks
can u give me your test images?

**Comment by ducbluee** [comment]
![4](https://user-images.githubusercontent.com/48615021/86116811-39a51f80-baf8-11ea-8a20-40eb11bc2cc7.jpg)
@myhub This image is faulty

**Comment by myhub** [comment]
I will test and then reply

**Comment by myhub** [comment]
I have tested it using test.py
![2020-06-30 20-04-44屏幕截图](https://user-images.githubusercontent.com/43366542/86124072-19339000-bb0d-11ea-93a2-ce6863b79232.png)

**Comment by ducbluee** [comment]
![1](https://user-images.githubusercontent.com/48615021/86194426-a8c25880-bb78-11ea-9d16-6d1fe4cf537b.jpg)
so bad, why did my error happen like this :(

**Comment by myhub** [comment]
it is better to limit the image size
you can refer to the code of test.py

**Comment by nissansz** [comment]
> ![1](https://user-images.githubusercontent.com/48615021/86194426-a8c25880-bb78-11ea-9d16-6d1fe4cf537b.jpg) so bad, why did my error happen like this :(

How to get Japanese crnn.bin? steve800018@gmail.com
