### ISSUE TITLE
The Coordinates are different from the actual coordinates of text

### ISSUE THREAD

**Issue by Ashish-Rout** [myhub/tr#78]
Sir, I was facing the problem coordinates in the previous version of tr were ok but now the coordinates are off quite a bit from the actual coordinates of text

**Comment by myhub** [comment]
can u give me your test image and code?

**Comment by Ashish-Rout** [comment]
Sir, here i have pasted the code as well as the image i am getting currently


from PIL import Image, ImageDraw, ImageFont
from tr import *
import cv2
def fun(img_path):
    ocr_path = img_path.split('.')[0]+'ocr.jpg'
    results=[]
    img_pil=Image.open(img_path)
    blank_pil = Image.new("L", img_pil.size, 255)
    blank_draw = ImageDraw.Draw(blank_pil)

    img_pil = Image.open(img_path)

    gray_pil = img_pil.convert("L")
    results = run(gray_pil)
    
    for line in results:
        x, y, w, h,angle = line[0]
        txt = line[1]
        font = ImageFont.truetype("arial.ttf", 12)
        blank_draw.text(xy=(x, y), text=txt, font=font)
    print('After Improving the Image Quality and saving it...')           # path_val=os.getcwd()
    blank_pil.save(ocr_path)

    return results
img_path = 'bs_c.png'
results = fun(img_path)
![bs_cocr](https://user-images.githubusercontent.com/67633350/86317143-505c8b00-bc4c-11ea-8a29-62f02a37493c.jpg)

**Comment by myhub** [comment]
I find the problem, 
the new version output the center of the text box, while the old version output the left-top coor of the text box

So you can change your code as 
`blank_draw.text(xy=(x - w/2, y - h/2), text=txt, font=font)`

**Comment by Ashish-Rout** [comment]
Thanks For The Information & code sir
