### ISSUE TITLE
Question in regards to the model

### ISSUE THREAD

**Issue by akashdeep90** [myhub/tr#8]
Hi there,

I liked the way you have implemented the OCR and I set it up in a docker container and I tested it out with multiple documents, worked really really well. I am happy to share the docker container file, so if anyone wants to set it up, they can do it in a minute. I am trying to make it work on my MAC, but even before that I was trying to figure out your code, not sure how you trained the model and how it is working. 

Can you please explain, how is the OCR working from tr.so file and what dataset you used to train your model? 

Akash

**Comment by myhub** [comment]
Thanks for your interest

More than 50% of the training samples is generated via software while some others is labeled manually.

I use a laptop with GTX1060 to train all the samples(more than 1,000 million), to speed up, I change the original CTPN/CRNN a little, for example, remove lstm, add resnet and reduce channels

The code use pytorch for training and libtorch for deploy
