### ISSUE TITLE
Without Internet Tr not working

### ISSUE THREAD

**Issue by Ashish-Rout** [myhub/tr#80]
Sir, I can't import tr without internet it is saying "no server available"

Thanks & Reg
![tr](https://user-images.githubusercontent.com/67633350/86557831-05f14c00-bf75-11ea-88fc-f1b1fe1b327a.png)

ards

**Comment by ysoup** [comment]
Hello, have you solved your problem? I have the same problem

**Comment by Ashish-Rout** [comment]
> Hello, have you solved your problem? I have the same problem

No, i haven't solved the problem as it requires the internet during init process after that it works offline.

**Comment by yuyoufine** [comment]
@myhub 大神  可以将连internet的这个环节去掉吗   封闭环境没法使用

**Comment by izhangh** [comment]
@myhub 大神，我想部署在内网环境，同求去掉internet初始化环节，谢谢^-^

**Comment by w-Bro** [comment]
@myhub Could you please remove the requirement of internet when impoting tr?It's a offline SDK, isn't it?
