### ISSUE TITLE
一个月前正常使用，现在突然报no server available

### ISSUE THREAD

**Issue by wangguanhua** [myhub/tr#86]
服务器网络正常，重新安装也不行，test.py也报该错误

**Comment by myhub** [comment]
应该不会的，除非网络不支持DNS域名解析

**Comment by wangguanhua** [comment]
服务器可以正常pip第三方库，证明网络没问题。然后我又换了台服务器，还是报一样的错误
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "myhub/tr"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月7日(星期五) 晚上6:12
收件人:&nbsp;"myhub/tr"<tr@noreply.github.com&gt;;
抄送:&nbsp;"767477036"<767477036@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [myhub/tr] 一个月前正常使用，现在突然报no server available (#86)





 
应该不会的，除非网络不支持DNS域名解析

**Comment by myhub** [comment]
我测试下

**Comment by myhub** [comment]
我这边运行正常的

**Comment by myhub** [comment]
会不会你那边关闭了一些DNS服务器，比如谷歌域名服务器 114域名服务器

**Comment by wangguanhua** [comment]
我这边测试结果是2.2.8版本运行正常




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "myhub/tr"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月7日(星期五) 晚上6:17
收件人:&nbsp;"myhub/tr"<tr@noreply.github.com&gt;;
抄送:&nbsp;"767477036"<767477036@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [myhub/tr] 一个月前正常使用，现在突然报no server available (#86)





 
会不会你那边关闭了一些DNS服务器，比如谷歌域名服务器 114域名服务器

**Comment by myhub** [comment]
最新的2.3.0测试不通过吗？

**Comment by wangguanhua** [comment]
就是报no server错误，也不知道为啥



---原始邮件---
发件人: "Dream"<notifications@github.com&gt;
发送时间: 2020年8月9日(周日) 上午8:28
收件人: "myhub/tr"<tr@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"wangguanhua"<767477036@qq.com&gt;;
主题: Re: [myhub/tr] 一个月前正常使用，现在突然报no server available (#86)




 
最新的2.3.0测试不通过吗？

**Comment by myhub** [comment]
新版本我测试了依然正常。程序初始化时只要DNS服务正常就不会报错的

**Comment by myhub** [comment]
我换了几台电脑，拉github上最新的代码测试，都是正常的
这个问题没法复现，我就close了

**Comment by yyyear** [comment]
遇到了相同的问题,   服务器有网 报no server available    
问题原因:  服务器封了 UDP 打开就好了
