### ISSUE TITLE
GPU版本的结果不稳定

### ISSUE THREAD

**Issue by zhongguohun** [myhub/tr#87]
运行几次之后，识别结果就不稳定了，很多字符识别不出来，重启之后又会好一些

**Comment by myhub** [comment]
应该不会吧，同样的输入 不管运行多少次，都会得到同样的输出

只有运行速度会由于CPU/GPU的负载会不稳定

**Comment by lixiaolong19890207** [comment]
我也遇到了这种情况，cpu模式下，同样的图片有时候能识别，有时候不能识别

**Comment by cenwei1234** [comment]
> 运行几次之后，识别结果就不稳定了，很多字符识别不出来，重启之后又会好一些

后来你解决了吗
