### ISSUE TITLE
适用于amrv7的libtr.so

### ISSUE THREAD

**Issue by YHYJ** [myhub/tr#88]
有适用于amrv7的libtr.so文件么，我构建arm/v7架构的docker镜像一直报错：
```bash
OSError: /usr/local/lib/python3.7/site-packages/tr/libtr.so: wrong ELF class: ELFCLASS64
```

**Comment by myhub** [comment]
这个暂时没有，目前仅仅依赖于 onnxruntime\opencv4，这2个第三方库应该是支持ARMv7的，理论上可以支持amrv7的，需要花时间来编译

**Comment by YHYJ** [comment]
这样的话是不是可以在最开始加一个架构判断，否则我辛辛苦苦把一大堆依赖包加进去，到最后报个架构不对，心态崩了呀

**Comment by myhub** [comment]
大部分的PC软件如果不特别说明，都是不支持ARMv7的呀
