### ISSUE TITLE
Image recognition with text in English

### ISSUE THREAD

**Issue by ducbluee** [myhub/tr#89]
In the character recognition for sentences using English, there are still errors such as mistaking i to l or i to j or j to i, hope the author can solve

**Comment by myhub** [comment]
yes. there still need many sample s to train the model

**Comment by ducbluee** [comment]
@myhub 
look forward to a new update soon

**Comment by nissansz** [comment]
> yes. there still need many more samples to train the model. which will solve the problem you mentioned

How to get Japanese crnn.bin? steve800018@gmail.com
