### ISSUE TITLE
run里面有bug

### ISSUE THREAD

**Issue by novioleo** [myhub/tr#9]
tr中run里面，如果没有文本或者没有检测出来文本，那么会返回None，在后面进行numpy的类型转换就会报错。

**Comment by myhub** [comment]
谢谢，会尽快修复BUG

**Comment by novioleo** [comment]
另外，我这没看到你加载模型，不知道模型是不是常驻内存的，走一个session机制好一点哈～ @myhub

**Comment by myhub** [comment]
因为模型很小，所以常驻内存的。这样API使用起来会很简单

**Comment by novioleo** [comment]
@myhub 有没有想过直接上fots。我是某fots的作者。。。大家可以py交易一波。

**Comment by myhub** [comment]
我目前用的还是几年前的CTPN/CRNN技术，这几天在专心优化CRNN，等识别精度提高了我再看看FOTS

**Comment by novioleo** [comment]
恩，确实，我16年都在用这个了。。23333。我之前也讨论过一些关于精度和泛化以及域自适应性问题，有机会可以多交流下。
