### ISSUE TITLE
采用gpu计算时第一次运行时间长

### ISSUE THREAD

**Issue by qiyuhou** [myhub/tr#90]
运行如下代码，两次运行gpu监控显示都调用了gpu，第二次开始时间很短。
```
start = time.time()
tr.run("r_channel.png")
print(time.time() - start)
start = time.time()
tr.run("r_channel.png")
print(time.time() - start)
# ...
```
请问是有缓存吗，这个缓存会保留多久？

**Comment by myhub** [comment]
不是缓存吧。也不清楚onnxruntime是如何工作的。跟代码无关

**Comment by qiyuhou** [comment]
> 不是缓存吧。也不清楚onnxruntime是如何工作的。onnxruntime可能是在第一次运行时有些初始化工作吧

启动后每跑一张新图片都是第二次以后很快，难道对每张图片都会有初始化吗，看起来感觉更像是有缓存。

**Comment by myhub** [comment]
可能是图片尺寸如果不一致，onnxruntime会先释放内存，再重新申请内存，导致时间的消耗

如果图片尺寸跟之前一致，就不用重新申请内存

你可以找个尺寸一样的不同图片测试下，就知道了

**Comment by qiyuhou** [comment]
> 可能是图片尺寸如果不一致，onnxruntime会先释放内存，再重新申请内存，导致时间的消耗
> 
> 如果图片尺寸跟之前一致，就不用重新申请内存
> 
> 你可以找个尺寸一样的不同图片测试下，就知道了

确实是这样，尺寸一致就没问题了
