### ISSUE TITLE
有没有办法在离线的情况运行

### ISSUE THREAD

**Issue by zzs269285304** [myhub/tr#92]
有没有办法在离线的情况启动程序，让它在脱离互联网的情况下启动。

**Comment by myhub** [comment]
离线启动目前是需要授权的，可以联系 anycode@yahoo.com

**Comment by yoorxee** [comment]
要是能离线就好了，支持国产

**Comment by blair2020** [comment]
作者在这有这个问题的回复;https://github.com/myhub/tr/issues/70#issuecomment-644479537
https://github.com/myhub/tr/releases/tag/1.5.1
旧版本可以完全离线运行，但可能效果那些没有2.0那么好
程序运行前先在tr-1.5.1/libtorch/lib路径下：
cat libtorch.so.part.* > libtorch.so
不然直接运行会报错

**Comment by scfw** [comment]
不能离线启动，这么重要的限制条件，作者也不明示，好坑啊

**Comment by myhub** [comment]
use v2.3.1
