### ISSUE TITLE
PyPI

### ISSUE THREAD

**Issue by blair2020** [myhub/tr#93]
我在https://pypi.org/project/tr/1.0.0.2/#description找到了作者的pip安装的
但是是pip install tr==1.0.0.2
github上是2.0版本，pypi上什么时候能有2.0版本
另外，通过pip install tr==1.0.0.2上安装的是不是就可以在win上运行？因为我试现在的github上的代码只能在linux上运行
望作者解惑

**Comment by myhub** [comment]
pip限制了安装包的大小不能超过60M，所以传不上去。

Windows的我之前编译了一个，后来闲麻烦就没更新Windows版本的了
