### ISSUE TITLE
Train crnn model

### ISSUE THREAD

**Issue by nampqaime** [myhub/tr#94]
Hello,

How can I train crnn model with my dataset.
Also, I have a .h5 model. So how can I convert my model to run with this repo?

Thanks!

**Comment by aki601** [comment]
Same question training our own model with our data can be done?
If possible how to implement it in this?

**Comment by nissansz** [comment]
> @myhub Same question training our own model with our data can be done? If possible how to implement it in this?

How to get Japanese crnn.bin? steve800018@gmail.com

**Comment by nissansz** [comment]
> Hello,
> 
> How can I train crnn model with my dataset. Also, I have a .h5 model. So how can I convert my model to run with this repo?
> 
> Thanks!

How to get Japanese crnn.bin? steve800018@gmail.com
