### ISSUE TITLE
如图，请教下，为何有时候明显同一行的识别内容会返回成不同行去呢？

### ISSUE THREAD

**Issue by lgs3137** [myhub/tr#97]
如图，请教下，为何有时候明显同一行的识别内容会返回成不同行去呢？
![image](https://user-images.githubusercontent.com/1278141/99222729-1f0ce200-281e-11eb-8d0b-61742d968ecb.png)

**Comment by lgs3137** [comment]
另外，可否把每行的起始坐标返回？这样的话比较方便分段文章内容识别后合并段落，现在只返回cx，xy的中心xy坐标，直接受到当前行内容的长度影响。

**Comment by myhub** [comment]
除了返回了文本行的中心坐标外，还返回了文本行的 长 宽 角度，可以算出每行的起始坐标的

当前的文本检测算法确实容易把一行分成两半

**Comment by lgs3137** [comment]
感谢~拆行的问题容易解决~比较下cy差就行~
起始行坐标的问题，我这边计算下看看~

**Comment by nissansz** [comment]
> 感谢~ 拆行的问题容易解决，比较下cy差就行~ 起始行坐标的问题，我这边计算下看看~

您好，怎样可以用的日文的crnn.bin文件？微信nlanguage
