### ISSUE TITLE
v2.3.0 未联网的情况下，不能正常使用

### ISSUE THREAD

**Issue by msben** [myhub/tr#99]
联系这个邮箱anycode@yahoo.com，未能得到回复，咨询下授权事宜。

**Comment by tangent2018** [comment]
仁兄有联系上吗，我也发了邮件，没得到回音

**Comment by myhub** [comment]
这个限制后面准备取消的，谢谢关注，不建议付费

**Comment by myhub** [comment]
use 2.3.1

**Comment by seanlee928** [comment]
> use 2.3.1

请问是2.3.1是已经去掉了联网了么
